// Generate idempotent SQL to (re)seed the PoE2 reference tables from the canonical data
// files, so the DB exactly matches what the overlay submits and the website reads.
//
//   jewel_types / conquerors  <- frontend/static/data/poe2/jewels.json
//   tree_notables             <- frontend/static/data/poe2/data.json (every notable: id, name)
//   vocab_notables            <- frontend/static/data/poe2/notables.json (result pool per jewel)
//
// Upserts only (ON CONFLICT DO UPDATE/NOTHING) — never deletes — so it's safe to run on
// the live DB and re-run after a game data update. Writes worker/scripts/reference_seed.sql.
//
// Run: node scripts/seed_reference.mjs

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const DATA = join(here, '..', '..', 'frontend', 'static', 'data', 'poe2');
const OUT = join(here, 'reference_seed.sql');

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const values = (rows) => rows.map((r) => `(${r.join(', ')})`).join(',\n  ');

const jewels = JSON.parse(readFileSync(join(DATA, 'jewels.json'), 'utf8'));
const tree = JSON.parse(readFileSync(join(DATA, 'data.json'), 'utf8'));
const notablesById = JSON.parse(readFileSync(join(DATA, 'notables.json'), 'utf8'));

// jewel_types: id = name (the value the overlay/website filter by).
const jewelRows = jewels.map((j) => [q(j.name), q(j.name), j.seedMin, j.seedMax]);

// conquerors: (jewel_type, name) for every variant.
const conqRows = jewels.flatMap((j) => j.variants.map((v) => [q(j.name), q(v.name)]));

// tree_notables: every notable node in the tree (deduped by string id).
const seen = new Set();
const treeRows = [];
for (const n of Object.values(tree.nodes)) {
  if (!n || !n.isNotable || n.isJewelSocket || typeof n.id !== 'string') continue;
  if (seen.has(n.id)) continue;
  seen.add(n.id);
  treeRows.push([q(n.id), q(n.name ?? '')]);
}

// vocab_notables: the result pool per jewel (jewel_type, id, name).
const vocabRows = jewels.flatMap((j) =>
  (notablesById[String(j.id)] ?? []).map((v) => [q(j.name), q(v.id), q(v.name)])
);

const sql = `-- Generated by worker/scripts/seed_reference.mjs — idempotent reference reseed.

INSERT INTO jewel_types (id, name, seed_min, seed_max) VALUES
  ${values(jewelRows)}
ON CONFLICT (id) DO UPDATE
  SET name = EXCLUDED.name, seed_min = EXCLUDED.seed_min, seed_max = EXCLUDED.seed_max;

INSERT INTO conquerors (jewel_type, name) VALUES
  ${values(conqRows)}
ON CONFLICT (jewel_type, name) DO NOTHING;

INSERT INTO tree_notables (node_id, name) VALUES
  ${values(treeRows)}
ON CONFLICT (node_id) DO UPDATE SET name = EXCLUDED.name;

INSERT INTO vocab_notables (jewel_type, id, name) VALUES
  ${values(vocabRows)}
ON CONFLICT (jewel_type, id) DO UPDATE SET name = EXCLUDED.name;
`;

writeFileSync(OUT, sql);
console.log(
  `wrote ${OUT}: jewel_types=${jewelRows.length}, conquerors=${conqRows.length}, ` +
    `tree_notables=${treeRows.length}, vocab_notables=${vocabRows.length}`
);
