// Prevents an extra console window on Windows in release.
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod ring;

use image::{imageops::FilterType, RgbaImage};
use ring::{detect, Jewel};
use serde::{Deserialize, Serialize};
use tauri::{Emitter, Manager};
use tauri_plugin_global_shortcut::{Code, GlobalShortcutExt, Modifiers, Shortcut, ShortcutState};

use std::sync::Mutex;

// Per-socket LOCAL SUBGRAPH (node positions + connector edges) within R_tree of
// each jewel socket, embedded at build time (generated by scripts/extract_graphs.mjs).
// This is the geometry we register against the screen capture to identify the
// socket — node positions/edges are stable, unlike node icon art under a jewel.
const SOCKET_GRAPHS_JSON: &str = include_str!("../../src/poe2_socket_graphs.json");

// Reference images of each jewel AS SOCKETED in-game (the gem + socket frame). The
// jewel type is identified by template-matching the captured ring centre against these,
// rather than by ring colour — the centre always shows the actual jewel, so this also
// rejects a false-positive ring (UI clutter) whose centre holds no matching jewel.
const HEROIC_REF_PNG: &[u8] = include_bytes!("../../../frontend/static/data/Jewel/Heroic-Tragedy-Socketed.png");
const UNDYING_REF_PNG: &[u8] = include_bytes!("../../../frontend/static/data/Jewel/Undying-Hate-Socketed.png");

fn heroic_ref() -> &'static RgbaImage {
    use std::sync::OnceLock;
    static R: OnceLock<RgbaImage> = OnceLock::new();
    R.get_or_init(|| {
        image::load_from_memory(HEROIC_REF_PNG)
            .expect("decode Heroic-Tragedy-Socketed.png")
            .to_rgba8()
    })
}

fn undying_ref() -> &'static RgbaImage {
    use std::sync::OnceLock;
    static R: OnceLock<RgbaImage> = OnceLock::new();
    R.get_or_init(|| {
        image::load_from_memory(UNDYING_REF_PNG)
            .expect("decode Undying-Hate-Socketed.png")
            .to_rgba8()
    })
}

// Serialises ALL screen captures. xcap uses DXGI desktop duplication on Windows,
// which crashes if two captures run concurrently — so every capture path (the
// detect loop and the debug-dump hotkey) takes this lock first.
static CAPTURE_LOCK: Mutex<()> = Mutex::new(());

#[derive(Deserialize)]
struct SocketGraphT {
    #[serde(rename = "socketId")]
    socket_id: i64,
    x: f64,
    y: f64,
    /// Renderable node positions (tree units) within R_tree of the socket.
    #[allow(dead_code)]
    nodes: Vec<[f64; 2]>,
    /// Connector edges among those nodes, as [x1, y1, x2, y2] in tree units.
    edges: Vec<[f64; 4]>,
}
#[derive(Deserialize)]
struct GraphData {
    #[serde(rename = "rTree")]
    r_tree: f64,
    sockets: Vec<SocketGraphT>,
}

/// A detected jewel ring, the auto-identified jewel + socket, and the captured
/// frame size. Ring/frame fields are in physical px (primary-monitor space).
#[derive(Serialize, Clone)]
struct Detection {
    cx: f64,
    cy: f64,
    r: f64,
    support: usize,
    coverage: f64,
    resid: f64,
    frame_w: u32,
    frame_h: u32,
    /// "Undying Hate" | "Heroic Tragedy".
    jewel: String,
    /// Template-match correlation (−1..1) of the centred jewel vs its reference image —
    /// how confidently `jewel` was identified. Higher = stronger match.
    jewel_match: f64,
    /// Matched socketed-jewel sprite WIDTH in px. A static, stable scale reference — the
    /// caller derives the projection scale from this, not the jittery ring radius `r`.
    gem: f64,
    /// Best-matching socket's graph id, or -1 if no confident match.
    socket_id: i64,
    /// Edge-chamfer cost of the best socket (mean px distance, LOWER = better).
    socket_score: f64,
    /// Chamfer cost of the runner-up — the gap is the confidence in socket_id.
    socket_second: f64,
}

#[derive(Serialize, Clone)]
struct CursorPos {
    x: f64,
    y: f64,
}

/// Parsed from the jewel's Ctrl+C item text. The seed is what makes a recording
/// meaningful — the same node in the same socket transforms differently per seed.
#[derive(Serialize, Clone)]
struct JewelInfo {
    /// "Heroic Tragedy" | "Undying Hate".
    jewel: String,
    seed: u32,
    /// The selected conqueror, e.g. "Vorana" (empty if not found).
    conqueror: String,
}

/// The seed is the integer immediately followed by its "(min-max)" range, e.g.
/// `Remembrancing 7704(100-8000) ...`. Scanning for that pattern is robust across
/// both jewels regardless of the surrounding flavour wording.
fn find_seed(text: &str) -> Option<u32> {
    let b = text.as_bytes();
    let n = b.len();
    let mut i = 0;
    while i < n {
        if !b[i].is_ascii_digit() {
            i += 1;
            continue;
        }
        let start = i;
        while i < n && b[i].is_ascii_digit() {
            i += 1;
        }
        // Require "(digits-digits)" immediately after the number.
        if i < n && b[i] == b'(' {
            let mut j = i + 1;
            let ds = j;
            while j < n && b[j].is_ascii_digit() {
                j += 1;
            }
            if j > ds && j < n && b[j] == b'-' {
                j += 1;
                let es = j;
                while j < n && b[j].is_ascii_digit() {
                    j += 1;
                }
                if j > es && j < n && b[j] == b')' {
                    return text[start..i].parse().ok();
                }
            }
        }
    }
    None
}

/// The selected conqueror from "...by the line of <Name>(<all variants>)".
fn find_conqueror(text: &str) -> Option<String> {
    const KEY: &str = "by the line of ";
    let p = text.find(KEY)? + KEY.len();
    let rest = &text[p..];
    let end = rest.find('(').unwrap_or(rest.len());
    let name = rest[..end].trim();
    (!name.is_empty()).then(|| name.to_string())
}

/// Parse a PoE2 timeless-jewel item-text clipboard string. Returns None if the text
/// isn't a timeless jewel or has no recognisable seed.
fn parse_jewel(text: &str) -> Option<JewelInfo> {
    if !text.contains("Timeless Jewel") {
        return None;
    }
    let lines: Vec<&str> = text.lines().map(|l| l.trim()).collect();
    // The jewel name is the line directly above "Timeless Jewel".
    let idx = lines.iter().position(|&l| l == "Timeless Jewel")?;
    if idx == 0 {
        return None;
    }
    let jewel = lines[idx - 1].to_string();
    let seed = find_seed(text)?;
    Some(JewelInfo {
        jewel,
        seed,
        conqueror: find_conqueror(text).unwrap_or_default(),
    })
}

fn graphs() -> &'static GraphData {
    use std::sync::OnceLock;
    static D: OnceLock<GraphData> = OnceLock::new();
    D.get_or_init(|| serde_json::from_str(SOCKET_GRAPHS_JSON).expect("valid poe2_socket_graphs.json"))
}

/// Sobel gradient-magnitude edge bitmap (true = edge pixel) over the RGBA capture.
/// Edges are the jewel-art-INDEPENDENT signal: node positions and the connector
/// lines between them don't change under a timeless jewel, so the tree's line
/// structure is a stable fingerprint. Threshold mirrors the offline harness
/// (Sobel magnitude > ~200 on 0..255 luminance), validated against `Screenshots/`.
fn edge_map(buf: &[u8], w: usize, h: usize, thr: f64) -> Vec<bool> {
    let mut lum = vec![0f32; w * h];
    for i in 0..w * h {
        let p = i * 4;
        lum[i] = (buf[p] as f32 + buf[p + 1] as f32 + buf[p + 2] as f32) / 3.0;
    }
    let mut edge = vec![false; w * h];
    for y in 1..h - 1 {
        for x in 1..w - 1 {
            let i = y * w + x;
            let (tl, tc, tr) = (lum[i - w - 1], lum[i - w], lum[i - w + 1]);
            let (ml, mr) = (lum[i - 1], lum[i + 1]);
            let (bl, bc, br) = (lum[i + w - 1], lum[i + w], lum[i + w + 1]);
            let gx = (tr + 2.0 * mr + br) - (tl + 2.0 * ml + bl);
            let gy = (bl + 2.0 * bc + br) - (tl + 2.0 * tc + tr);
            if ((gx * gx + gy * gy).sqrt() as f64) > thr {
                edge[i] = true;
            }
        }
    }
    edge
}

/// Two-pass chamfer distance transform: each cell holds the approximate distance
/// (in pixels) to the nearest edge pixel. 3-4 chamfer weights approximate
/// Euclidean distance; dividing by 3 converts the integer weights to ~pixel units.
/// This lets us score a projected model against the edge map with one lookup per
/// sample — robust to faint/broken lines because near-misses still score low.
fn distance_transform(edge: &[bool], w: usize, h: usize) -> Vec<f32> {
    const BIG: f32 = 1e9;
    const D3: f32 = 3.0;
    const D4: f32 = 4.0;
    let mut d = vec![BIG; w * h];
    for i in 0..w * h {
        if edge[i] {
            d[i] = 0.0;
        }
    }
    for y in 0..h {
        for x in 0..w {
            let i = y * w + x;
            let mut v = d[i];
            if x > 0 {
                v = v.min(d[i - 1] + D3);
            }
            if y > 0 {
                v = v.min(d[i - w] + D3);
                if x > 0 {
                    v = v.min(d[i - w - 1] + D4);
                }
                if x + 1 < w {
                    v = v.min(d[i - w + 1] + D4);
                }
            }
            d[i] = v;
        }
    }
    for y in (0..h).rev() {
        for x in (0..w).rev() {
            let i = y * w + x;
            let mut v = d[i];
            if x + 1 < w {
                v = v.min(d[i + 1] + D3);
            }
            if y + 1 < h {
                v = v.min(d[i + w] + D3);
                if x + 1 < w {
                    v = v.min(d[i + w + 1] + D4);
                }
                if x > 0 {
                    v = v.min(d[i + w - 1] + D4);
                }
            }
            d[i] = v;
        }
    }
    for v in d.iter_mut() {
        *v /= 3.0;
    }
    d
}

/// Mean chamfer distance of a socket's projected connector EDGES to the captured
/// edge map. Each edge is sampled every ~6px and the distance-transform value
/// under each sample is averaged; samples projected outside the ring/frame are
/// skipped. The correct socket's edges align with real tree lines, so its mean
/// distance is the LOWEST. (Replaces the old node-brightness heuristic, which the
/// jewel's changed node art made unreliable.)
fn score_socket_edges(
    dt: &[f32],
    w: usize,
    h: usize,
    cx: f64,
    cy: f64,
    r: f64,
    r_tree: f64,
    sock: &SocketGraphT,
) -> f64 {
    let s = r / r_tree;
    let step = 6.0;
    let mut sum = 0.0;
    let mut n = 0usize;
    for e in &sock.edges {
        let ax = cx + (e[0] - sock.x) * s;
        let ay = cy + (e[1] - sock.y) * s;
        let bx = cx + (e[2] - sock.x) * s;
        let by = cy + (e[3] - sock.y) * s;
        let seg = ((bx - ax).powi(2) + (by - ay).powi(2)).sqrt();
        let steps = (seg / step).max(2.0) as usize;
        for k in 0..=steps {
            let t = k as f64 / steps as f64;
            let px = ax + (bx - ax) * t;
            let py = ay + (by - ay) * t;
            if ((px - cx).powi(2) + (py - cy).powi(2)).sqrt() > r {
                continue;
            }
            let (ix, iy) = (px as i64, py as i64);
            if ix < 0 || iy < 0 || ix as usize >= w || iy as usize >= h {
                continue;
            }
            sum += dt[iy as usize * w + ix as usize] as f64;
            n += 1;
        }
    }
    if n == 0 {
        1e9
    } else {
        sum / n as f64
    }
}

/// Pearson correlation of a reference jewel sprite (placed centred at cx,cy) against the
/// captured RGBA frame, over the reference's OPAQUE pixels and all three colour channels.
/// Correlating R,G,B jointly (one global mean) keeps the relative colour signature — the
/// blue Heroic gem vs the gold Undying eye anti-correlate — so this captures both shape
/// and colour. Returns None if too little of the sprite is on-screen.
fn zncc_rgb(buf: &[u8], w: usize, h: usize, cx: f64, cy: f64, reference: &RgbaImage, stride: i64) -> Option<f64> {
    let (rw, rh) = (reference.width() as i64, reference.height() as i64);
    let ox = cx.round() as i64 - rw / 2;
    let oy = cy.round() as i64 - rh / 2;
    let (mut sa, mut sb, mut saa, mut sbb, mut sab, mut n) = (0.0, 0.0, 0.0, 0.0, 0.0, 0.0f64);
    let mut ry = 0;
    while ry < rh {
        let mut rx = 0;
        while rx < rw {
            let p = reference.get_pixel(rx as u32, ry as u32).0;
            let (sx, sy) = (ox + rx, oy + ry);
            // Skip transparent sprite corners and any sample off-screen.
            if p[3] >= 40 && sx >= 0 && sy >= 0 && (sx as usize) < w && (sy as usize) < h {
                let ci = (sy as usize * w + sx as usize) * 4;
                for ch in 0..3 {
                    let (a, b) = (p[ch] as f64, buf[ci + ch] as f64);
                    sa += a;
                    sb += b;
                    saa += a * a;
                    sbb += b * b;
                    sab += a * b;
                    n += 1.0;
                }
            }
            rx += stride;
        }
        ry += stride;
    }
    if n < 300.0 {
        return None;
    }
    let cov = sab - sa * sb / n;
    let den = ((saa - sa * sa / n) * (sbb - sb * sb / n)).sqrt();
    (den > 1e-6).then(|| cov / den)
}

// Resize the reference to a given on-screen WIDTH (keeping aspect) for matching.
fn scaled_ref(reference: &RgbaImage, width: u32) -> RgbaImage {
    let rh = (width as f64 * reference.height() as f64 / reference.width() as f64).round() as u32;
    image::imageops::resize(reference, width, rh.max(1), FilterType::Triangle)
}

/// Locate the socketed jewel precisely by template-matching its reference around the ring
/// centre, returning (cx, cy, gem_px, score). The gem is a STATIC, high-contrast feature,
/// so BOTH its correlation-peak position and its matched pixel SIZE are far steadier than
/// the animated ring's circle fit (which jitters frame-to-frame, badly when zoomed out).
/// `gem_px` is the matched sprite width in pixels — a stable scale reference the caller
/// uses instead of the noisy ring radius. A low score means the gem isn't at the ring
/// centre (a false-positive ring, or lost lock); the caller treats that as a bad frame.
fn locate_jewel(
    buf: &[u8],
    w: usize,
    h: usize,
    ring_cx: f64,
    ring_cy: f64,
    r: f64,
    reference: &RgbaImage,
) -> (f64, f64, f64, f64) {
    // 1) Coarse: pick the scale (as a fraction of the ring radius) that best matches at the
    //    ring centre, to seed the position + fine-scale searches.
    let (mut d0, mut coarse_score) = (0u32, f64::NEG_INFINITY);
    for f in [0.12, 0.15, 0.18, 0.21, 0.24] {
        let diam = (r * f) as u32;
        if diam < 16 {
            continue;
        }
        if let Some(s) = zncc_rgb(buf, w, h, ring_cx, ring_cy, &scaled_ref(reference, diam), 2) {
            if s > coarse_score {
                coarse_score = s;
                d0 = diam;
            }
        }
    }
    if d0 == 0 {
        return (ring_cx, ring_cy, 0.0, f64::NEG_INFINITY);
    }
    // 2) Position: search a small window around the ring centre for the correlation peak.
    let coarse = scaled_ref(reference, d0);
    let half = (r * 0.05).clamp(8.0, 24.0) as i64;
    let (mut cx, mut cy) = (ring_cx, ring_cy);
    let mut pos_score = coarse_score;
    let mut dy = -half;
    while dy <= half {
        let mut dx = -half;
        while dx <= half {
            let (px, py) = (ring_cx + dx as f64, ring_cy + dy as f64);
            if let Some(s) = zncc_rgb(buf, w, h, px, py, &coarse, 2) {
                if s > pos_score {
                    pos_score = s;
                    cx = px;
                    cy = py;
                }
            }
            dx += 2;
        }
        dy += 2;
    }
    // 3) Fine SCALE: at the refined centre, sweep absolute widths around d0 to measure the
    //    gem's true pixel size. Searching absolute px (not a fraction of the jittery ring
    //    radius) makes gem_px depend only on the static gem — so it's stable frame-to-frame.
    let (mut gem_px, mut best_score) = (d0 as f64, pos_score);
    let lo = ((d0 as f64) * 0.82) as u32;
    let hi = ((d0 as f64) * 1.18) as u32;
    let mut width = lo.max(16);
    while width <= hi {
        if let Some(s) = zncc_rgb(buf, w, h, cx, cy, &scaled_ref(reference, width), 2) {
            if s > best_score {
                best_score = s;
                gem_px = width as f64;
            }
        }
        width += 2;
    }
    (cx, cy, gem_px, best_score)
}

/// Capture the primary monitor, auto-detect the jewel (by matching the socketed jewel at
/// the ring centre to its reference image), the ring geometry, and which socket it sits
/// in. Returns None when no ring is found.
///
/// `identify` controls the (heavier) socket scoring: pass `true` until the socket
/// is locked, then `false` so subsequent frames only do the cheap ring transform
/// (resolve-once-then-lock). When `false`, `socket_id` is returned as -1.
#[tauri::command]
fn capture_and_detect(identify: bool) -> Result<Option<Detection>, String> {
    let _guard = CAPTURE_LOCK.lock().map_err(|_| "capture lock poisoned")?;
    let monitors = xcap::Monitor::all().map_err(|e| e.to_string())?;
    let monitor = monitors
        .into_iter()
        .find(|m| m.is_primary())
        .ok_or("no primary monitor")?;
    let img = monitor.capture_image().map_err(|e| e.to_string())?;
    let (w, h) = (img.width(), img.height());
    let buf = img.as_raw();

    // Detect each jewel's coloured ring, then identify the jewel by template-matching the
    // socketed gem at that ring's centre against its reference image. The correct jewel's
    // centre holds its gem (high correlation); a false-positive ring (blue mana orb, a
    // drawn annotation) has no matching gem at its centre (low correlation), so this both
    // labels the jewel and rejects bogus rings — more reliable than ring-colour support.
    let candidates = [
        (Jewel::UndyingHate, "Undying Hate", undying_ref()),
        (Jewel::HeroicTragedy, "Heroic Tragedy", heroic_ref()),
    ];
    // For each jewel's ring, locate its gem: refined centre, matched pixel size, and score.
    // The reported centre is the GEM peak (a static feature → stable centre), and the gem
    // size is the scale reference — both steadier than the ring's circle fit.
    let mut best: Option<(ring::Circle, f64, f64, f64, &str, f64)> = None; // circle, gem_cx, gem_cy, gem_px, name, score
    for (kind, name, reference) in candidates {
        if let Some(c) = detect(buf, w, h, kind) {
            let (gx, gy, gpx, score) = locate_jewel(buf, w as usize, h as usize, c.cx, c.cy, c.r, reference);
            let better = match best.as_ref() {
                None => true,
                Some((.., bs)) => score > *bs,
            };
            if better {
                best = Some((c, gx, gy, gpx, name, score));
            }
        }
    }
    let Some((c, gem_cx, gem_cy, gem_px, jewel, jewel_match)) = best else {
        return Ok(None);
    };

    // Identify the socket by edge-chamfer registration over all 14 sockets — only
    // when asked (resolve-once-then-lock: the UI stops requesting once it locks a
    // socket, so steady-state frames pay just the cheap ring transform).
    let (wu, hu) = (w as usize, h as usize);
    let (mut socket_id, mut socket_score, mut socket_second) = (-1i64, 0.0f64, 0.0f64);
    if identify {
        let g = graphs();
        let edge = edge_map(buf, wu, hu, 200.0);
        let dt = distance_transform(&edge, wu, hu);
        // Lower chamfer cost = better geometric fit.
        let mut bests = (-1i64, f64::INFINITY);
        let mut second = f64::INFINITY;
        for sock in &g.sockets {
            let sc = score_socket_edges(&dt, wu, hu, gem_cx, gem_cy, c.r, g.r_tree, sock);
            if sc < bests.1 {
                second = bests.1;
                bests = (sock.socket_id, sc);
            } else if sc < second {
                second = sc;
            }
        }
        socket_score = bests.1;
        socket_second = second;
        // Confidence gate: only commit when the runner-up is clearly worse (real
        // rings separate by >10%); otherwise stay unresolved (-1) and let the user
        // cycle, rather than locking onto a wrong socket on an ambiguous frame.
        if bests.1.is_finite() && second.is_finite() && second > bests.1 * 1.06 {
            socket_id = bests.0;
        }
    }

    Ok(Some(Detection {
        cx: gem_cx,
        cy: gem_cy,
        r: c.r,
        support: c.support,
        coverage: c.coverage,
        resid: c.resid,
        frame_w: w,
        frame_h: h,
        jewel: jewel.to_string(),
        jewel_match,
        gem: gem_px,
        socket_id,
        socket_score,
        socket_second,
    }))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dt_single_edge_pixel() {
        // One edge pixel at the centre of a 5x5 grid; 3-4 chamfer /3 should give
        // 0 at the pixel, 1.0 orthogonally, 4/3 diagonally, 2.0 two steps away.
        let (w, h) = (5usize, 5usize);
        let mut edge = vec![false; w * h];
        edge[2 * w + 2] = true;
        let d = distance_transform(&edge, w, h);
        let at = |x: usize, y: usize| d[y * w + x];
        assert!((at(2, 2) - 0.0).abs() < 1e-4);
        assert!((at(2, 1) - 1.0).abs() < 1e-4, "orthogonal = 3/3");
        assert!((at(1, 1) - 4.0 / 3.0).abs() < 1e-4, "diagonal = 4/3");
        assert!((at(2, 0) - 2.0).abs() < 1e-4, "two orthogonal = 6/3");
    }

    #[test]
    fn jewel_match_prefers_correct_reference() {
        // Paint the Heroic reference into a synthetic capture at a known centre/scale,
        // then confirm it scores higher against the Heroic reference than the Undying one.
        let href = heroic_ref();
        let (w, h) = (400usize, 400usize);
        let (cx, cy, r) = (200.0, 200.0, 200.0);
        let diam = (r * 0.16) as u32; // matches a scale in jewel_match_score's search
        let rh = (diam as f64 * href.height() as f64 / href.width() as f64).round() as u32;
        let scaled = image::imageops::resize(href, diam, rh, FilterType::Triangle);
        let mut buf = vec![0u8; w * h * 4];
        let ox = cx as i64 - scaled.width() as i64 / 2;
        let oy = cy as i64 - scaled.height() as i64 / 2;
        for ry in 0..scaled.height() {
            for rx in 0..scaled.width() {
                let p = scaled.get_pixel(rx, ry).0;
                if p[3] < 40 {
                    continue;
                }
                let (sx, sy) = (ox + rx as i64, oy + ry as i64);
                let ci = (sy as usize * w + sx as usize) * 4;
                buf[ci] = p[0];
                buf[ci + 1] = p[1];
                buf[ci + 2] = p[2];
                buf[ci + 3] = 255;
            }
        }
        let (lx, ly, gpx, sh) = locate_jewel(&buf, w, h, cx, cy, r, heroic_ref());
        let (.., su) = locate_jewel(&buf, w, h, cx, cy, r, undying_ref());
        assert!(sh > su, "heroic match {sh} should beat undying {su}");
        assert!(sh > 0.5, "self-match should be strong: {sh}");
        // The located centre should snap back to where the gem was painted.
        assert!((lx - cx).abs() <= 4.0 && (ly - cy).abs() <= 4.0, "located ({lx},{ly}) vs ({cx},{cy})");
        // The measured gem width should be close to what was painted (diam).
        assert!((gpx - diam as f64).abs() <= 6.0, "gem px {gpx} vs painted {diam}");
    }

    #[test]
    fn parses_heroic_tragedy_clipboard() {
        let text = "Item Class: Jewels\r\nRarity: Unique\r\nHeroic Tragedy\r\nTimeless Jewel\r\n--------\r\nLimited to: 1 Historic\r\nRadius: Very Large\r\n--------\r\nItem Level: 84\r\n--------\r\n{ Unique Modifier }\r\nHistoric — Unscalable Value\r\nRemembrancing 7704(100-8000) songworthy deeds by the line of Vorana(Vorana-Olroth)\r\nPassives in radius are Conquered by the Kalguur — Unscalable Value\r\n";
        let j = parse_jewel(text).expect("should parse");
        assert_eq!(j.jewel, "Heroic Tragedy");
        assert_eq!(j.seed, 7704);
        assert_eq!(j.conqueror, "Vorana");
    }

    #[test]
    fn rejects_non_jewel_text() {
        assert!(parse_jewel("just some clipboard text 1234(5-6)").is_none());
    }

    #[test]
    fn chamfer_score_rewards_aligned_edges() {
        // DT = vertical distance to the horizontal line y = 10.
        let (w, h) = (100usize, 100usize);
        let mut dt = vec![0f32; w * h];
        for y in 0..h {
            for x in 0..w {
                dt[y * w + x] = (y as f32 - 10.0).abs();
            }
        }
        // s = r/r_tree = 1; ring centre (50,50); socket at the tree origin.
        let (cx, cy, r, r_tree) = (50.0, 50.0, 100.0, 100.0);
        // Edge projecting onto screen y = 10 (right on the line) -> ~0 cost.
        let aligned = SocketGraphT {
            socket_id: 1,
            x: 0.0,
            y: 0.0,
            nodes: vec![],
            edges: vec![[-30.0, -40.0, 30.0, -40.0]],
        };
        // Edge projecting onto screen y = 60 (~50px off the line) -> high cost.
        let off = SocketGraphT {
            socket_id: 2,
            x: 0.0,
            y: 0.0,
            nodes: vec![],
            edges: vec![[-30.0, 10.0, 30.0, 10.0]],
        };
        let sa = score_socket_edges(&dt, w, h, cx, cy, r, r_tree, &aligned);
        let so = score_socket_edges(&dt, w, h, cx, cy, r, r_tree, &off);
        assert!(sa < 0.5, "aligned edge sits on the line: {sa}");
        assert!(so > 40.0, "off edge is ~50px away: {so}");
        assert!(sa < so);
    }
}

/// Global cursor position in physical px (matches the capture/ring coordinate space).
#[tauri::command]
fn get_cursor(app: tauri::AppHandle) -> Result<CursorPos, String> {
    let p = app.cursor_position().map_err(|e| e.to_string())?;
    Ok(CursorPos { x: p.x, y: p.y })
}

/// Read the jewel's Ctrl+C item text from the OS clipboard and parse it. Returns
/// None when the clipboard doesn't hold a recognisable timeless jewel.
#[tauri::command]
fn read_jewel() -> Result<Option<JewelInfo>, String> {
    let mut cb = arboard::Clipboard::new().map_err(|e| e.to_string())?;
    let text = cb.get_text().map_err(|e| e.to_string())?;
    Ok(parse_jewel(&text))
}

/// Debug: save a raw primary-monitor capture to a PNG so detection masks can be
/// tuned against the user's real graphics settings. Returns the saved path.
fn save_debug_capture() -> Result<String, String> {
    let _guard = CAPTURE_LOCK.lock().map_err(|_| "capture lock poisoned")?;
    let monitors = xcap::Monitor::all().map_err(|e| e.to_string())?;
    let monitor = monitors
        .into_iter()
        .find(|m| m.is_primary())
        .ok_or("no primary monitor")?;
    let img = monitor.capture_image().map_err(|e| e.to_string())?;
    let mut path = std::env::temp_dir();
    path.push("poe2_overlay_capture.png");
    img.save(&path).map_err(|e| e.to_string())?;
    Ok(path.to_string_lossy().to_string())
}

fn main() {
    // Disable GPU compositing for the WebView2 surface — transparent layered
    // windows on Windows 11 intermittently crash on creation with hardware
    // compositing enabled. This is the standard remedy.
    std::env::set_var("WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS", "--disable-gpu");

    // Ctrl+Shift+J: record node + advance. Ctrl+Shift+K: start/stop.
    // Ctrl+Shift+S: dump a debug screen capture for mask tuning.
    let capture_key = Shortcut::new(Some(Modifiers::CONTROL | Modifiers::SHIFT), Code::KeyJ);
    let toggle_key = Shortcut::new(Some(Modifiers::CONTROL | Modifiers::SHIFT), Code::KeyK);
    let dump_key = Shortcut::new(Some(Modifiers::CONTROL | Modifiers::SHIFT), Code::KeyS);
    // Manual socket cycling — auto-detect seeds the guess, these correct it.
    let prev_key = Shortcut::new(Some(Modifiers::CONTROL | Modifiers::SHIFT), Code::BracketLeft);
    let next_key = Shortcut::new(Some(Modifiers::CONTROL | Modifiers::SHIFT), Code::BracketRight);
    // Ctrl+Shift+C: ingest the jewel's Ctrl+C item text (jewel type + seed).
    let jewel_key = Shortcut::new(Some(Modifiers::CONTROL | Modifiers::SHIFT), Code::KeyC);

    tauri::Builder::default()
        .plugin(
            tauri_plugin_global_shortcut::Builder::new()
                .with_handler(move |app, sc, event| {
                    if event.state() != ShortcutState::Pressed {
                        return;
                    }
                    if sc == &capture_key {
                        let _ = app.emit("capture-hotkey", ());
                    } else if sc == &toggle_key {
                        let _ = app.emit("toggle-run", ());
                    } else if sc == &dump_key {
                        match save_debug_capture() {
                            Ok(p) => {
                                let _ = app.emit("debug-capture", p);
                            }
                            Err(e) => {
                                let _ = app.emit("debug-capture", format!("ERROR: {e}"));
                            }
                        }
                    } else if sc == &prev_key {
                        let _ = app.emit("socket-cycle", -1i32);
                    } else if sc == &next_key {
                        let _ = app.emit("socket-cycle", 1i32);
                    } else if sc == &jewel_key {
                        let _ = app.emit("read-jewel", ());
                    }
                })
                .build(),
        )
        .invoke_handler(tauri::generate_handler![
            capture_and_detect,
            get_cursor,
            read_jewel
        ])
        .setup(move |app| {
            let gs = app.global_shortcut();
            gs.register(capture_key)?;
            gs.register(toggle_key)?;
            gs.register(dump_key)?;
            gs.register(prev_key)?;
            gs.register(next_key)?;
            gs.register(jewel_key)?;
            if let Some(win) = app.get_webview_window("main") {
                // Permanently click-through: the overlay never intercepts input, so
                // it can't lock the screen or steal focus from the game. We do NOT
                // resize/move the window here — the transparent layered window is
                // created at its final size in tauri.conf.json, because resizing a
                // transparent window after creation crashes WebView2 on Windows.
                let _ = win.set_ignore_cursor_events(true);
            }
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
