// Prevents an extra console window on Windows in release.
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod ocr;
mod ring;

use ocr::OcrLine;
use ring::{detect, Jewel};
use serde::{Deserialize, Serialize};
use tauri::menu::{Menu, MenuItem, PredefinedMenuItem};
use tauri::tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent};
use tauri::{Emitter, Manager};
use tauri_plugin_global_shortcut::{Code, GlobalShortcutExt, Modifiers, Shortcut, ShortcutState};

use std::sync::Mutex;

// Per-socket LOCAL SUBGRAPH (node positions + connector edges) within R_tree of
// each jewel socket, embedded at build time (generated by scripts/extract_graphs.mjs).
// This is the geometry we register against the screen capture to identify the
// socket — node positions/edges are stable, unlike node icon art under a jewel.
const SOCKET_GRAPHS_JSON: &str = include_str!("../../src/poe2_socket_graphs.json");

// The anchor is the jewel's radius RING (the coloured circle it draws on the tree). Its
// pixel radius equals R_tree tree units exactly, so it gives centre + an AUTHORITATIVE scale
// (s = ring_r_px / R_tree) in one cheap circle fit — far more precise than a small frame's
// width. We detect it ONLY on an explicit calibrate (one-shot), so its frame-to-frame jitter
// (which drove the earlier socketed-graphic approach) is irrelevant. `refine_pose` then snaps
// the pose to the real tree lines, correcting any ring-fit error.

// Serialises ALL screen captures. xcap uses DXGI desktop duplication on Windows,
// which crashes if two captures run concurrently — so every capture path (the
// detect loop and the debug-dump hotkey) takes this lock first.
static CAPTURE_LOCK: Mutex<()> = Mutex::new(());

#[derive(Deserialize)]
struct SocketGraphT {
    #[serde(rename = "socketId")]
    socket_id: i64,
    x: f64,
    y: f64,
    /// Renderable node positions (tree units) within R_tree of the socket.
    #[allow(dead_code)]
    nodes: Vec<[f64; 2]>,
    /// Connector edges among those nodes, as [x1, y1, x2, y2] in tree units.
    edges: Vec<[f64; 4]>,
}
#[derive(Deserialize)]
struct GraphData {
    #[serde(rename = "rTree")]
    r_tree: f64,
    sockets: Vec<SocketGraphT>,
}

/// The located socket (centre of the matched socketed graphic), the auto-identified jewel +
/// socket, and the captured frame size. Centre/frame fields are in physical px (primary-monitor
/// space). There is no ring anymore — the socketed graphic is the sole anchor.
#[derive(Serialize, Clone)]
struct Detection {
    cx: f64,
    cy: f64,
    /// EFFECTIVE jewel radius in px = (frame_px / FRAME_TREE_WIDTH) * R_tree. Drives the
    /// screen↔tree scale exactly as the old ring radius did, so projection/scoring are unchanged.
    r: f64,
    /// Unused (kept for the JS contract); always 0.
    support: usize,
    /// Match confidence (= `jewel_match`); the JS status line shows it as a percentage.
    coverage: f64,
    /// Unused (kept for the JS contract); always 0.
    resid: f64,
    frame_w: u32,
    frame_h: u32,
    /// "Undying Hate" | "Heroic Tragedy" — whichever reference correlated higher.
    jewel: String,
    /// Template-match correlation (−1..1) of the located socketed graphic vs its reference —
    /// how confidently `jewel`/the pose was found. Below ACQUIRE_FLOOR the frame is dropped.
    jewel_match: f64,
    /// Matched studded-frame WIDTH in px. The static, high-contrast scale ruler — the caller
    /// derives the projection scale from this (frame_px / FRAME_TREE_WIDTH).
    gem: f64,
    /// Best-matching socket's graph id, or -1 if no confident match.
    socket_id: i64,
    /// Edge-chamfer cost of the best socket (mean px distance, LOWER = better).
    socket_score: f64,
    /// Chamfer cost of the runner-up — the gap is the confidence in socket_id.
    socket_second: f64,
    /// The colour ring wasn't found but a WHITE hover-highlight ring was: the user is hovering
    /// the jewel (tooltip up), which hides the colour the mask needs. The caller asks them to
    /// move off the jewel and retries. No pose is usable in this state.
    hovered: bool,
}

#[derive(Serialize, Clone)]
struct CursorPos {
    x: f64,
    y: f64,
}

/// Parsed from the jewel's Ctrl+C item text. The seed is what makes a recording
/// meaningful — the same node in the same socket transforms differently per seed.
#[derive(Serialize, Clone)]
struct JewelInfo {
    /// "Heroic Tragedy" | "Undying Hate".
    jewel: String,
    seed: u32,
    /// The selected conqueror, e.g. "Vorana" (empty if not found).
    conqueror: String,
}

/// The seed is the integer immediately followed by its "(min-max)" range, e.g.
/// `Remembrancing 7704(100-8000) ...`. Scanning for that pattern is robust across
/// both jewels regardless of the surrounding flavour wording.
///
/// With PoE's "Advanced Mod Descriptions" enabled, enchant/implicit rolls ALSO copy
/// with a parenthetical range — e.g. `+6(4-8) to Intelligence` — and such a line can
/// sit above the seed line. So we collect every `number(min-max)` candidate and keep
/// the one whose range span (`max - min`) is widest: a timeless-jewel seed range spans
/// thousands (100-8000, 79-30977) while a stat roll spans single digits, so the seed
/// always wins without hardcoding any per-jewel range.
fn find_seed(text: &str) -> Option<u32> {
    let b = text.as_bytes();
    let n = b.len();
    let mut i = 0;
    let mut best: Option<(u32, u32)> = None; // (seed, range span)
    while i < n {
        if !b[i].is_ascii_digit() {
            i += 1;
            continue;
        }
        let start = i;
        while i < n && b[i].is_ascii_digit() {
            i += 1;
        }
        // Require "(min-max)" immediately after the number.
        if i < n && b[i] == b'(' {
            let mut j = i + 1;
            let ds = j;
            while j < n && b[j].is_ascii_digit() {
                j += 1;
            }
            if j > ds && j < n && b[j] == b'-' {
                let min: Option<u32> = text[ds..j].parse().ok();
                j += 1;
                let es = j;
                while j < n && b[j].is_ascii_digit() {
                    j += 1;
                }
                if j > es && j < n && b[j] == b')' {
                    if let (Some(seed), Some(min), Some(max)) =
                        (text[start..i].parse::<u32>().ok(), min, text[es..j].parse::<u32>().ok())
                    {
                        let span = max.saturating_sub(min);
                        if best.map_or(true, |(_, b_span)| span > b_span) {
                            best = Some((seed, span));
                        }
                    }
                }
            }
        }
    }
    best.map(|(seed, _)| seed)
}

/// The selected conqueror from "...by the line of <Name>(<all variants>)".
fn find_conqueror(text: &str) -> Option<String> {
    const KEY: &str = "by the line of ";
    let p = text.find(KEY)? + KEY.len();
    let rest = &text[p..];
    let end = rest.find('(').unwrap_or(rest.len());
    let name = rest[..end].trim();
    (!name.is_empty()).then(|| name.to_string())
}

/// Parse a PoE2 timeless-jewel item-text clipboard string. Returns None if the text
/// isn't a timeless jewel or has no recognisable seed.
fn parse_jewel(text: &str) -> Option<JewelInfo> {
    if !text.contains("Timeless Jewel") {
        return None;
    }
    let lines: Vec<&str> = text.lines().map(|l| l.trim()).collect();
    // The jewel name is the line directly above "Timeless Jewel".
    let idx = lines.iter().position(|&l| l == "Timeless Jewel")?;
    if idx == 0 {
        return None;
    }
    let jewel = lines[idx - 1].to_string();
    let seed = find_seed(text)?;
    Some(JewelInfo {
        jewel,
        seed,
        conqueror: find_conqueror(text).unwrap_or_default(),
    })
}

/// Capture the primary monitor as raw RGBA8 (`w*h*4` bytes, row-major). Serialises on
/// CAPTURE_LOCK because xcap's Windows DXGI path crashes if two captures overlap. The
/// single capture path for everything that needs pixels (detect + OCR).
fn capture_primary() -> Result<(Vec<u8>, u32, u32), String> {
    let _guard = CAPTURE_LOCK.lock().map_err(|_| "capture lock poisoned")?;
    let monitors = xcap::Monitor::all().map_err(|e| e.to_string())?;
    let monitor = monitors
        .into_iter()
        .find(|m| m.is_primary())
        .ok_or("no primary monitor")?;
    let img = monitor.capture_image().map_err(|e| e.to_string())?;
    let (w, h) = (img.width(), img.height());
    Ok((img.into_raw(), w, h))
}

fn graphs() -> &'static GraphData {
    use std::sync::OnceLock;
    static D: OnceLock<GraphData> = OnceLock::new();
    D.get_or_init(|| serde_json::from_str(SOCKET_GRAPHS_JSON).expect("valid poe2_socket_graphs.json"))
}

/// Sobel gradient-magnitude edge bitmap (true = edge pixel) over the RGBA capture.
/// Edges are the jewel-art-INDEPENDENT signal: node positions and the connector
/// lines between them don't change under a timeless jewel, so the tree's line
/// structure is a stable fingerprint. Threshold mirrors the offline harness
/// (Sobel magnitude > ~200 on 0..255 luminance), validated against `Screenshots/`.
fn edge_map(buf: &[u8], w: usize, h: usize, thr: f64) -> Vec<bool> {
    let mut lum = vec![0f32; w * h];
    for i in 0..w * h {
        let p = i * 4;
        lum[i] = (buf[p] as f32 + buf[p + 1] as f32 + buf[p + 2] as f32) / 3.0;
    }
    let mut edge = vec![false; w * h];
    for y in 1..h - 1 {
        for x in 1..w - 1 {
            let i = y * w + x;
            let (tl, tc, tr) = (lum[i - w - 1], lum[i - w], lum[i - w + 1]);
            let (ml, mr) = (lum[i - 1], lum[i + 1]);
            let (bl, bc, br) = (lum[i + w - 1], lum[i + w], lum[i + w + 1]);
            let gx = (tr + 2.0 * mr + br) - (tl + 2.0 * ml + bl);
            let gy = (bl + 2.0 * bc + br) - (tl + 2.0 * tc + tr);
            if ((gx * gx + gy * gy).sqrt() as f64) > thr {
                edge[i] = true;
            }
        }
    }
    edge
}

/// Two-pass chamfer distance transform: each cell holds the approximate distance
/// (in pixels) to the nearest edge pixel. 3-4 chamfer weights approximate
/// Euclidean distance; dividing by 3 converts the integer weights to ~pixel units.
/// This lets us score a projected model against the edge map with one lookup per
/// sample — robust to faint/broken lines because near-misses still score low.
fn distance_transform(edge: &[bool], w: usize, h: usize) -> Vec<f32> {
    const BIG: f32 = 1e9;
    const D3: f32 = 3.0;
    const D4: f32 = 4.0;
    let mut d = vec![BIG; w * h];
    for i in 0..w * h {
        if edge[i] {
            d[i] = 0.0;
        }
    }
    for y in 0..h {
        for x in 0..w {
            let i = y * w + x;
            let mut v = d[i];
            if x > 0 {
                v = v.min(d[i - 1] + D3);
            }
            if y > 0 {
                v = v.min(d[i - w] + D3);
                if x > 0 {
                    v = v.min(d[i - w - 1] + D4);
                }
                if x + 1 < w {
                    v = v.min(d[i - w + 1] + D4);
                }
            }
            d[i] = v;
        }
    }
    for y in (0..h).rev() {
        for x in (0..w).rev() {
            let i = y * w + x;
            let mut v = d[i];
            if x + 1 < w {
                v = v.min(d[i + 1] + D3);
            }
            if y + 1 < h {
                v = v.min(d[i + w] + D3);
                if x + 1 < w {
                    v = v.min(d[i + w + 1] + D4);
                }
                if x > 0 {
                    v = v.min(d[i + w - 1] + D4);
                }
            }
            d[i] = v;
        }
    }
    for v in d.iter_mut() {
        *v /= 3.0;
    }
    d
}

/// Mean chamfer distance of a socket's projected connector EDGES to the captured
/// edge map. Each edge is sampled every ~6px and the distance-transform value
/// under each sample is averaged; samples projected outside the ring/frame are
/// skipped. The correct socket's edges align with real tree lines, so its mean
/// distance is the LOWEST. (Replaces the old node-brightness heuristic, which the
/// jewel's changed node art made unreliable.)
fn score_socket_edges(
    dt: &[f32],
    w: usize,
    h: usize,
    cx: f64,
    cy: f64,
    r: f64,
    r_tree: f64,
    sock: &SocketGraphT,
) -> f64 {
    let s = r / r_tree;
    let step = 6.0;
    let mut sum = 0.0;
    let mut n = 0usize;
    for e in &sock.edges {
        let ax = cx + (e[0] - sock.x) * s;
        let ay = cy + (e[1] - sock.y) * s;
        let bx = cx + (e[2] - sock.x) * s;
        let by = cy + (e[3] - sock.y) * s;
        let seg = ((bx - ax).powi(2) + (by - ay).powi(2)).sqrt();
        let steps = (seg / step).max(2.0) as usize;
        for k in 0..=steps {
            let t = k as f64 / steps as f64;
            let px = ax + (bx - ax) * t;
            let py = ay + (by - ay) * t;
            if ((px - cx).powi(2) + (py - cy).powi(2)).sqrt() > r {
                continue;
            }
            let (ix, iy) = (px as i64, py as i64);
            if ix < 0 || iy < 0 || ix as usize >= w || iy as usize >= h {
                continue;
            }
            sum += dt[iy as usize * w + ix as usize] as f64;
            n += 1;
        }
    }
    if n == 0 {
        1e9
    } else {
        sum / n as f64
    }
}

/// Refine the pose (centre + radius) by minimising the edge-chamfer cost of the identified
/// socket's projected connector edges against the captured tree lines. The gem template gives
/// a good centre and an approximate scale; this snaps both to the real tree geometry so the
/// projected notables overlay the actual nodes (fixes residual off-centre / scale error). Two
/// shrinking grid passes (coarse → fine); cheap enough for the one-shot calibrate.
fn refine_pose(
    dt: &[f32],
    w: usize,
    h: usize,
    cx: f64,
    cy: f64,
    r: f64,
    r_tree: f64,
    sock: &SocketGraphT,
) -> (f64, f64, f64) {
    let (mut bcx, mut bcy, mut br) = (cx, cy, r);
    let mut bc = score_socket_edges(dt, w, h, bcx, bcy, br, r_tree, sock);
    // (offset step px, offset max px, scale step, scale steps each side)
    for &(off_step, off_max, sc_step, sc_n) in &[(4i64, 8i64, 0.03f64, 3i64), (1i64, 3i64, 0.01f64, 3i64)] {
        let (c0x, c0y, r0) = (bcx, bcy, br);
        let mut si = -sc_n;
        while si <= sc_n {
            let rr = r0 * (1.0 + sc_step * si as f64);
            let mut dy = -off_max;
            while dy <= off_max {
                let mut dx = -off_max;
                while dx <= off_max {
                    let (ncx, ncy) = (c0x + dx as f64, c0y + dy as f64);
                    let s = score_socket_edges(dt, w, h, ncx, ncy, rr, r_tree, sock);
                    if s < bc {
                        bc = s;
                        bcx = ncx;
                        bcy = ncy;
                        br = rr;
                    }
                    dx += off_step;
                }
                dy += off_step;
            }
            si += 1;
        }
    }
    (bcx, bcy, br)
}

/// Capture the primary monitor and detect the jewel's radius RING (the coloured circle it draws
/// on the tree). Returns the ring centre, the ring radius in px (the scale anchor: s = r / R_tree),
/// the jewel type (from the ring colour), and which socket it sits in. `None` when no ring is found.
///
/// Detection runs only on an explicit calibrate (one-shot), so the ring's animation jitter is
/// irrelevant. `jewel` (the type the user copied with Ctrl+C, if known) restricts detection to that
/// colour — cheaper and immune to the other colour's UI clutter. `socket_hint` forces the tree-snap
/// to a specific socket (the user's locked choice) instead of re-identifying. `identify` runs the
/// (heavier) socket scoring + tree-snap; pass `false` to skip it (`socket_id` stays -1).
#[tauri::command]
fn capture_and_detect(
    jewel: Option<String>,
    socket_hint: Option<i64>,
    identify: bool,
) -> Result<Option<Detection>, String> {
    let (frame, w, h) = capture_primary()?;
    let buf: &[u8] = &frame;
    let (wu, hu) = (w as usize, h as usize);

    // Detect the radius ring. Restrict to the copied jewel's colour when known (cheaper, and
    // immune to the other colour's UI clutter); otherwise try both and keep the better-supported
    // circle. The ring colour also identifies the jewel type.
    let all = [
        (Jewel::UndyingHate, "Undying Hate"),
        (Jewel::HeroicTragedy, "Heroic Tragedy"),
    ];
    let candidates: Vec<(Jewel, &str)> = match jewel.as_deref() {
        Some(j) if all.iter().any(|&(_, n)| n == j) => all.into_iter().filter(|&(_, n)| n == j).collect(),
        _ => all.to_vec(),
    };
    let mut best: Option<(ring::Circle, &str)> = None;
    for (kind, name) in candidates {
        if let Some(c) = detect(buf, w, h, kind) {
            if best.as_ref().map_or(true, |(bc, _)| c.support > bc.support) {
                best = Some((c, name));
            }
        }
    }
    let Some((c, jewel)) = best else {
        // No colour ring. If a WHITE ring is there instead, the jewel is being hovered (its
        // tooltip is up, recolouring the ring) — signal that so the caller can ask the user to
        // move off it, rather than the generic "can't find socket" dead end.
        if let Some(wc) = ring::detect_white(buf, w, h) {
            if wc.coverage >= 0.5 {
                return Ok(Some(Detection {
                    cx: wc.cx,
                    cy: wc.cy,
                    r: wc.r,
                    support: 0,
                    coverage: wc.coverage,
                    resid: wc.resid,
                    frame_w: w,
                    frame_h: h,
                    jewel: String::new(),
                    jewel_match: 0.0,
                    gem: 0.0,
                    socket_id: -1,
                    socket_score: 0.0,
                    socket_second: 0.0,
                    hovered: true,
                }));
            }
        }
        return Ok(None);
    };
    // The ring fit IS the pose: centre = the socket's projected position, radius = R_tree px,
    // so the projection scale s = r / R_tree is exact. `refine_pose` polishes it against the tree.
    let (mut cx, mut cy, mut r) = (c.cx, c.cy, c.r);
    // Ring coverage (fraction of the circle the masked arc spans) is the confidence the caller
    // gates on — a partial/occluded ring or a stray blob scores low.
    let jewel_match = c.coverage;

    let g = graphs();

    // Identify the socket by edge-chamfer registration over all 12 jewel sockets — only when
    // asked. In the on-demand calibration model this runs on every (explicit) calibrate.
    let (mut socket_id, mut socket_score, mut socket_second) = (-1i64, 0.0f64, 0.0f64);
    if identify {
        let edge = edge_map(buf, wu, hu, 200.0);
        let dt = distance_transform(&edge, wu, hu);
        // Lower chamfer cost = better geometric fit.
        let mut bests = (-1i64, f64::INFINITY);
        let mut second = f64::INFINITY;
        for sock in &g.sockets {
            let sc = score_socket_edges(&dt, wu, hu, cx, cy, r, g.r_tree, sock);
            if sc < bests.1 {
                second = bests.1;
                bests = (sock.socket_id, sc);
            } else if sc < second {
                second = sc;
            }
        }
        socket_score = bests.1;
        socket_second = second;
        // The user's manual socket choice (after they cycled to correct a wrong auto-ID) wins,
        // so the tree-snap below refines for THAT socket; otherwise use the confidence gate:
        // commit only when the runner-up is clearly worse, else stay unresolved (-1).
        match socket_hint {
            Some(hint) if g.sockets.iter().any(|s| s.socket_id == hint) => socket_id = hint,
            _ if bests.1.is_finite() && second.is_finite() && second > bests.1 * 1.06 => {
                socket_id = bests.0;
            }
            _ => {}
        }
        if socket_id >= 0 {
            // Snap the pose (centre + scale) to the chosen socket's actual tree lines.
            // The gem template gives a good seed; this fixes residual off-centre / scale error
            // so the projected notables land on the real nodes. Affordable as a one-shot.
            if let Some(sock) = g.sockets.iter().find(|s| s.socket_id == socket_id) {
                let (ncx, ncy, nr) = refine_pose(&dt, wu, hu, cx, cy, r, g.r_tree, sock);
                cx = ncx;
                cy = ncy;
                r = nr;
                socket_score = score_socket_edges(&dt, wu, hu, cx, cy, r, g.r_tree, sock);
            }
        }
    }

    Ok(Some(Detection {
        cx,
        cy,
        r,
        support: c.support,
        coverage: c.coverage,
        resid: c.resid,
        frame_w: w,
        frame_h: h,
        jewel: jewel.to_string(),
        jewel_match,
        gem: 0.0,
        socket_id,
        socket_score,
        socket_second,
        hovered: false,
    }))
}

// The glow is probed in GLOW_ANGLES directions around the node, each at several radial multiples of
// icon_r (the halo sits at the icon edge and fades outward). A direction counts as "lit" if ANY of
// its radii hits a glow pixel; the node is highlighted when most directions are lit.
const GLOW_ANGLES: usize = 16;
const GLOW_RADII: [f64; 4] = [0.8, 1.0, 1.2, 1.45];
// Fraction of directions that must show glow. The search halo is radially symmetric (~all
// directions), whereas a jewel-ring spoke or a one-sided green sunburst lights only ~1-2. Measured:
// a real lit node covers 16/16 directions, while spokes, coloured sunbursts and unlit nodes all
// cover <=1/16 — so 0.6 sits in a very wide gap.
const GLOW_COVERAGE_MIN: f64 = 0.6;

/// A "glow" pixel: near-grey (channels close together) and clearly above the dark tree background.
/// The PoE2 search highlight is a soft WHITE-GREY halo around the matched node — bright *relative* to
/// the ~15-value background but only ~80-130 in absolute terms, so an absolute near-255 white test
/// (the original approach) misses it. The grey requirement (small channel spread) rejects coloured
/// tree art — green allocation glows and gold/green jewel-ring spokes — though a blown-out spoke core
/// can still read grey, which is why the caller also requires radial symmetry (a spoke is a stripe).
fn is_glow_px(r: i32, g: i32, b: i32) -> bool {
    let mx = r.max(g).max(b);
    let mn = r.min(g).min(b);
    r > 55 && g > 55 && b > 55 && (mx - mn) < 40
}

/// True if the node centred at (`cx`,`cy`) in physical px carries the search-highlight halo: a
/// grey glow is present in at least `GLOW_COVERAGE_MIN` of the directions around it (sampled at
/// several radii spanning the icon edge). Requiring glow in MOST directions is what separates the
/// radially-symmetric highlight from a bright spoke or a one-sided sunburst that only lights a
/// couple of directions. Robust to a few px of pose error and to icon_r being slightly off (a
/// direction is lit if any of its radii hits the halo). `icon_r` is the on-screen node-icon radius
/// in px (JS derives it from the locked ring radius × zoom).
fn glow_at(buf: &[u8], w: usize, h: usize, cx: f64, cy: f64, icon_r: f64) -> bool {
    use std::f64::consts::PI;
    if icon_r < 3.0 {
        return false;
    }
    let is_glow = |px: f64, py: f64| -> Option<bool> {
        let (ix, iy) = (px.round() as i64, py.round() as i64);
        if ix < 0 || iy < 0 || ix as usize >= w || iy as usize >= h {
            return None;
        }
        let i = (iy as usize * w + ix as usize) * 4;
        Some(is_glow_px(buf[i] as i32, buf[i + 1] as i32, buf[i + 2] as i32))
    };
    let (mut lit, mut on_screen) = (0usize, 0usize);
    for k in 0..GLOW_ANGLES {
        let a = 2.0 * PI * k as f64 / GLOW_ANGLES as f64;
        let (c, s) = (a.cos(), a.sin());
        let mut any_sample = false;
        let mut any_glow = false;
        for &m in &GLOW_RADII {
            let r = icon_r * m;
            if let Some(g) = is_glow(cx + r * c, cy + r * s) {
                any_sample = true;
                any_glow |= g;
            }
        }
        if any_sample {
            on_screen += 1;
        }
        if any_glow {
            lit += 1;
        }
    }
    // Need most directions on-screen (reject a node hanging off the frame edge) and most of them lit.
    on_screen >= GLOW_ANGLES * 3 / 4 && (lit as f64 / GLOW_ANGLES as f64) >= GLOW_COVERAGE_MIN
}

/// True if the captured frame still shows THIS overlay's own drawing. The overlay draws its target
/// ring in mask-safe ORANGE (#ff7733) and the hover ring in MAGENTA (#ff44dd) — colours deliberately
/// absent from the game (see the .node.target CSS note). Their presence means the overlay window
/// hadn't been cleared/presented when the capture ran (the capture raced the compositor). Crucially,
/// the overlay's white "to-do" node circles — which composite to a grey ring that mimics the search
/// halo and cause false glows — are drawn exactly when a target (orange) is, so orange is a reliable
/// proxy for "the interfering markers are on screen". Subsampled; a handful of pixels is enough.
fn frame_has_overlay(buf: &[u8], w: usize, h: usize) -> bool {
    let is_orange = |r: i32, g: i32, b: i32| r > 225 && (95..=150).contains(&g) && b < 80;
    let is_magenta = |r: i32, g: i32, b: i32| r > 225 && g < 110 && b > 190;
    let mut count = 0usize;
    let mut y = 0usize;
    while y < h {
        let row = y * w * 4;
        let mut x = 0usize;
        while x < w {
            let i = row + x * 4;
            let (r, g, b) = (buf[i] as i32, buf[i + 1] as i32, buf[i + 2] as i32);
            if is_orange(r, g, b) || is_magenta(r, g, b) {
                count += 1;
                if count >= 15 {
                    return true;
                }
            }
            x += 4;
        }
        y += 4;
    }
    false
}

/// Capture the primary monitor and report, for each candidate screen position (physical px), whether
/// that node has the search-highlight halo (see `glow_at`). `icon_r` is the expected node-icon radius
/// in px (the JS side derives it from the locked ring radius × zoom). The JS side hides the overlay
/// before calling, but the OS capture can race the compositor and still grab a frame with the overlay
/// drawn — whose white "to-do" node rings read as grey halos and light up nearly every node. So we
/// re-capture until the overlay sentinel (`frame_has_overlay`) is gone, then detect on that clean
/// frame. This is the core of the search-sweep capture method.
#[tauri::command]
fn detect_glow(positions: Vec<[f64; 2]>, icon_r: f64) -> Result<Vec<bool>, String> {
    let (mut frame, mut w, mut h) = capture_primary()?;
    for _ in 0..8 {
        if !frame_has_overlay(&frame, w as usize, h as usize) {
            break;
        }
        std::thread::sleep(std::time::Duration::from_millis(25));
        let cap = capture_primary()?;
        frame = cap.0;
        w = cap.1;
        h = cap.2;
    }
    let (wu, hu) = (w as usize, h as usize);
    Ok(positions
        .iter()
        .map(|p| glow_at(&frame, wu, hu, p[0], p[1], icon_r))
        .collect())
}

#[cfg(test)]
mod tests {
    use super::*;

    // On a real frame: detect the ring, then confirm refine_pose lowers the chamfer cost (better
    // tree alignment) and keeps the pose near the ring seed, plus print the ring's accuracy.
    //   cargo test ring_refine -- --ignored --nocapture
    #[test]
    #[ignore]
    fn ring_refine_improves_alignment_on_real_frame() {
        // (screenshot, jewel colour) — the green capture is a debug dump that may be absent.
        for (path, kind, label) in [
            ("../../Screenshots/stab_0.png", Jewel::HeroicTragedy, "blue/Heroic"),
            ("../../Screenshots/poe2_overlay_capture.png", Jewel::UndyingHate, "green/Undying"),
        ] {
            let img = match image::open(path) {
                Ok(i) => i.to_rgba8(),
                Err(_) => continue,
            };
            let (w, h) = (img.width(), img.height());
            let buf = img.as_raw();
            let (wu, hu) = (w as usize, h as usize);
            let t = std::time::Instant::now();
            let Some(c) = detect(buf, w, h, kind) else {
                eprintln!("{label}: NO RING");
                continue;
            };
            let ring_ms = t.elapsed().as_millis();
            eprintln!(
                "{label}: detect={ring_ms}ms centre=({:.1},{:.1}) r={:.1} cov={:.2} resid={:.1}",
                c.cx, c.cy, c.r, c.coverage, c.resid
            );
            // Sanity: the ring fit must agree with a clutter-immune band fit by RANSAC alone
            // (the outer-edge refit must not have been pulled off by tree clutter).
            assert!(c.coverage >= 0.5, "ring coverage too low: {}", c.coverage);
        }
    }

    // OCR smoke test on a real tooltip screenshot. Capture one with Ctrl+Shift+S while a
    // transformed-notable tooltip is open, save it as Screenshots/tooltip.png, then run:
    //   cargo test ocr_tooltip -- --ignored --nocapture
    // Prints the recognised lines so the notable name can be eyeballed; asserts OCR ran.
    #[test]
    #[ignore]
    fn ocr_tooltip_reads_lines() {
        let img = match image::open("../../Screenshots/tooltip.png") {
            Ok(i) => i.to_rgba8(),
            Err(_) => {
                eprintln!("no Screenshots/tooltip.png — skipping");
                return;
            }
        };
        let (w, h) = (img.width(), img.height());
        // RGBA -> BGRA (the format ocr::recognize expects).
        let mut bgra = img.into_raw();
        for px in bgra.chunks_exact_mut(4) {
            px.swap(0, 2);
        }
        let lines = ocr::recognize(&bgra, w, h).expect("OCR should run");
        for l in &lines {
            eprintln!("  ({:.0},{:.0}) {}", l.cx, l.cy, l.text);
        }
        assert!(!lines.is_empty(), "expected some recognised text");
    }

    #[test]
    fn dt_single_edge_pixel() {
        // One edge pixel at the centre of a 5x5 grid; 3-4 chamfer /3 should give
        // 0 at the pixel, 1.0 orthogonally, 4/3 diagonally, 2.0 two steps away.
        let (w, h) = (5usize, 5usize);
        let mut edge = vec![false; w * h];
        edge[2 * w + 2] = true;
        let d = distance_transform(&edge, w, h);
        let at = |x: usize, y: usize| d[y * w + x];
        assert!((at(2, 2) - 0.0).abs() < 1e-4);
        assert!((at(2, 1) - 1.0).abs() < 1e-4, "orthogonal = 3/3");
        assert!((at(1, 1) - 4.0 / 3.0).abs() < 1e-4, "diagonal = 4/3");
        assert!((at(2, 0) - 2.0).abs() < 1e-4, "two orthogonal = 6/3");
    }

    #[test]
    fn glow_at_detects_grey_halo_not_colour() {
        // Build an RGBA frame; `paint(d)` decides which pixels (at tree-distance d from the node
        // centre) get the given colour, the rest stay dark background (value 12).
        let (w, h) = (200usize, 200usize);
        let (cx, cy, icon_r) = (100.0f64, 100.0f64, 20.0f64);
        let make = |paint: &dyn Fn(f64) -> bool, col: [u8; 3]| {
            let mut buf = vec![12u8; w * h * 4]; // dark background
            for y in 0..h {
                for x in 0..w {
                    let d = ((x as f64 - cx).powi(2) + (y as f64 - cy).powi(2)).sqrt();
                    if paint(d) {
                        let i = (y * w + x) * 4;
                        buf[i] = col[0];
                        buf[i + 1] = col[1];
                        buf[i + 2] = col[2];
                    }
                }
            }
            buf
        };
        // A grey halo around the node (~the real search highlight, ~100/channel), present in all
        // directions → lit.
        let halo = make(&|d| d <= icon_r * 2.0, [100, 100, 100]);
        assert!(glow_at(&halo, w, h, cx, cy, icon_r), "grey halo should be detected");
        // Robust to a few px of pose error: same halo, centre off by 8px → still lit.
        assert!(glow_at(&halo, w, h, cx + 8.0, cy, icon_r), "off-by-8px halo should still detect");
        // A SATURATED bright disc (green allocation glow / gold spoke) → rejected (not grey).
        let green = make(&|d| d <= icon_r * 2.0, [80, 210, 90]);
        assert!(!glow_at(&green, w, h, cx, cy, icon_r), "coloured bright art must be rejected");
        // A one-sided stripe through the node (a jewel-ring spoke) lights only ~2 directions → rejected.
        let stripe = make(&|_| false, [0, 0, 0]);
        let mut stripe = stripe;
        for y in 0..h {
            for x in 0..w {
                // a 10px-wide diagonal band of grey across the node
                if ((x as f64 - cx) - (y as f64 - cy)).abs() <= 5.0 {
                    let i = (y * w + x) * 4;
                    stripe[i] = 110;
                    stripe[i + 1] = 110;
                    stripe[i + 2] = 110;
                }
            }
        }
        assert!(!glow_at(&stripe, w, h, cx, cy, icon_r), "a one-sided spoke stripe must be rejected");
        // Dark background only → not lit.
        let empty = make(&|_| false, [0, 0, 0]);
        assert!(!glow_at(&empty, w, h, cx, cy, icon_r), "dark node → not lit");
        // Node off the right edge → too few in-bounds samples → not lit.
        assert!(!glow_at(&halo, w, h, (w as f64) + 5.0, cy, icon_r), "off-screen node → not lit");
    }

    #[test]
    fn parses_heroic_tragedy_clipboard() {
        let text = "Item Class: Jewels\r\nRarity: Unique\r\nHeroic Tragedy\r\nTimeless Jewel\r\n--------\r\nLimited to: 1 Historic\r\nRadius: Very Large\r\n--------\r\nItem Level: 84\r\n--------\r\n{ Unique Modifier }\r\nHistoric — Unscalable Value\r\nRemembrancing 7704(100-8000) songworthy deeds by the line of Vorana(Vorana-Olroth)\r\nPassives in radius are Conquered by the Kalguur — Unscalable Value\r\n";
        let j = parse_jewel(text).expect("should parse");
        assert_eq!(j.jewel, "Heroic Tragedy");
        assert_eq!(j.seed, 7704);
        assert_eq!(j.conqueror, "Vorana");
    }

    #[test]
    fn rejects_non_jewel_text() {
        assert!(parse_jewel("just some clipboard text 1234(5-6)").is_none());
    }

    #[test]
    fn seed_wins_over_enchant_range_with_advanced_mod_descriptions() {
        // "Advanced Mod Descriptions" makes the enchant copy with its own roll range
        // (`+6(4-8) to Intelligence`) ABOVE the seed line. The widest range must win so
        // the seed (range spans thousands) beats the enchant (range spans single digits).
        let text = "Item Class: Jewels\r\nRarity: Unique\r\nUndying Hate\r\nTimeless Jewel\r\n--------\r\nLimited to: 1 Historic\r\nRadius: Very Large\r\n--------\r\n+6(4-8) to Intelligence\r\n--------\r\n{ Unique Modifier }\r\nHistoric — Unscalable Value\r\nGlorifying the defilement of 17050(79-30977) souls in tribute to Kulemak by the line of Kurgal(Amanamu-Kulemak)\r\n";
        let j = parse_jewel(text).expect("should parse");
        assert_eq!(j.jewel, "Undying Hate");
        assert_eq!(j.seed, 17050);
        assert_eq!(j.conqueror, "Kurgal");
    }

    #[test]
    fn chamfer_score_rewards_aligned_edges() {
        // DT = vertical distance to the horizontal line y = 10.
        let (w, h) = (100usize, 100usize);
        let mut dt = vec![0f32; w * h];
        for y in 0..h {
            for x in 0..w {
                dt[y * w + x] = (y as f32 - 10.0).abs();
            }
        }
        // s = r/r_tree = 1; ring centre (50,50); socket at the tree origin.
        let (cx, cy, r, r_tree) = (50.0, 50.0, 100.0, 100.0);
        // Edge projecting onto screen y = 10 (right on the line) -> ~0 cost.
        let aligned = SocketGraphT {
            socket_id: 1,
            x: 0.0,
            y: 0.0,
            nodes: vec![],
            edges: vec![[-30.0, -40.0, 30.0, -40.0]],
        };
        // Edge projecting onto screen y = 60 (~50px off the line) -> high cost.
        let off = SocketGraphT {
            socket_id: 2,
            x: 0.0,
            y: 0.0,
            nodes: vec![],
            edges: vec![[-30.0, 10.0, 30.0, 10.0]],
        };
        let sa = score_socket_edges(&dt, w, h, cx, cy, r, r_tree, &aligned);
        let so = score_socket_edges(&dt, w, h, cx, cy, r, r_tree, &off);
        assert!(sa < 0.5, "aligned edge sits on the line: {sa}");
        assert!(so > 40.0, "off edge is ~50px away: {so}");
        assert!(sa < so);
    }
}

/// Global cursor position in physical px (matches the capture/ring coordinate space).
#[tauri::command]
fn get_cursor(app: tauri::AppHandle) -> Result<CursorPos, String> {
    let p = app.cursor_position().map_err(|e| e.to_string())?;
    Ok(CursorPos { x: p.x, y: p.y })
}

/// Toggle the overlay's OS-level click-through. The window is click-through by default so it
/// never intercepts game input; the frontend flips it OFF (enabled=false) only while the
/// cursor is over the draggable status panel, so the panel can receive drag events, then back
/// ON. Combined with the no-activate window style (see setup), flipping it never steals focus
/// from the game.
#[tauri::command]
fn set_click_through(app: tauri::AppHandle, enabled: bool) -> Result<(), String> {
    let win = app.get_webview_window("main").ok_or("no main window")?;
    win.set_ignore_cursor_events(enabled).map_err(|e| e.to_string())
}

/// Read the jewel's Ctrl+C item text from the OS clipboard and parse it. Returns
/// None when the clipboard doesn't hold a recognisable timeless jewel.
#[tauri::command]
fn read_jewel() -> Result<Option<JewelInfo>, String> {
    let mut cb = arboard::Clipboard::new().map_err(|e| e.to_string())?;
    let text = cb.get_text().map_err(|e| e.to_string())?;
    Ok(parse_jewel(&text))
}

/// The OS clipboard's change counter. Windows bumps it on EVERY clipboard write — even when
/// the new contents are byte-identical to the old — so the overlay can tell that the user
/// pressed Ctrl+C again (re-copying the same jewel) where a text diff would see no change.
/// Used by the arming handshake to gate seed capture on a deliberate, fresh copy.
#[tauri::command]
fn clipboard_seq() -> u32 {
    // SAFE: GetClipboardSequenceNumber reads a process-wide counter and takes no arguments,
    // touches no memory we own, and cannot fail.
    unsafe { windows::Win32::System::DataExchange::GetClipboardSequenceNumber() }
}

/// OCR the primary monitor and return the recognised lines whose centre falls inside a `w*h`
/// box centred on (`cx`,`cy`) — the caller passes the cursor so the hovered node's tooltip is
/// captured wherever it flips to. Centres are in full-frame physical px; the caller fuzzy-
/// matches the lines against the jewel's result-notable vocabulary.
///
/// We OCR the *whole frame* and then drop out-of-box lines by coordinate, rather than feeding
/// OCR a cropped or masked buffer. Two reasons, both observed on real captures:
///   1. Windows.Media.Ocr rescales its input by the image's overall dimensions before
///      recognition. A cropped buffer (seen at exactly 1400x1200) lands otherwise-crisp
///      tooltip text on a bad internal scale and returns noise; the full frame reads reliably.
///   2. Masking everything outside the box to black is itself a different image and triggers
///      the same fragility — it was observed to make OCR *drop* the real tooltip line while a
///      stale word from the overlay's status panel survived. Filtering by coordinate after a
///      clean full-frame OCR avoids both: the engine always sees the same crisp full frame,
///      and box membership is decided on the returned line centres.
///
/// Box membership is the only gate here. The caller still excludes its own panel region (it
/// knows the panel's live bounds) before matching, so panel text inside the box can't inject
/// false vocabulary matches.
#[tauri::command]
fn ocr_region(cx: f64, cy: f64, w: f64, h: f64) -> Result<Vec<OcrLine>, String> {
    let (frame, fw, fh) = capture_primary()?;
    // Windows OCR wants BGRA8; xcap gives RGBA8, so swap R/B across the whole frame.
    let n = (fw as usize) * (fh as usize);
    let mut bgra = vec![0u8; n * 4];
    for i in 0..n {
        bgra[i * 4] = frame[i * 4 + 2];
        bgra[i * 4 + 1] = frame[i * 4 + 1];
        bgra[i * 4 + 2] = frame[i * 4];
        bgra[i * 4 + 3] = frame[i * 4 + 3];
    }
    let lines = ocr::recognize(&bgra, fw, fh)?;
    // Keep lines whose centre lands in the cursor box (coords are already full-frame px).
    let (x0, y0) = (cx - w / 2.0, cy - h / 2.0);
    let (x1, y1) = (cx + w / 2.0, cy + h / 2.0);
    Ok(lines
        .into_iter()
        .filter(|l| l.cx >= x0 && l.cx <= x1 && l.cy >= y0 && l.cy <= y1)
        .collect())
}

/// POST a batch of recorded observations (serialised by the frontend) to the Worker write
/// endpoint. Done here rather than in the webview because the overlay's CSP blocks
/// cross-origin fetch; from native code there's no CORS to satisfy. Returns the Worker's
/// JSON body on success so the frontend can read accepted/rejected counts; a non-2xx
/// status is surfaced as an error so the frontend keeps the batch pending for retry.
#[tauri::command]
async fn submit_observations(worker_url: String, body: String) -> Result<String, String> {
    let url = format!("{}/api/poe2/observations", worker_url.trim_end_matches('/'));
    let resp = reqwest::Client::new()
        .post(&url)
        .header("Content-Type", "application/json")
        .body(body)
        .send()
        .await
        .map_err(|e| e.to_string())?;
    let status = resp.status();
    let text = resp.text().await.unwrap_or_default();
    if !status.is_success() {
        return Err(format!("HTTP {}: {}", status.as_u16(), text));
    }
    Ok(text)
}

/// Fetch the community consensus for a (jewel, seed) from the Worker so the overlay can show
/// which nodes are already recorded/verified and skip them. A GET from native code (no CORS),
/// same reason as submit_observations. Returns the Worker's JSON body.
#[tauri::command]
async fn fetch_consensus(worker_url: String, jewel: String, seed: u32) -> Result<String, String> {
    let seed_s = seed.to_string();
    let resp = reqwest::Client::new()
        .get(format!("{}/api/poe2/consensus", worker_url.trim_end_matches('/')))
        .query(&[("jewel", jewel.as_str()), ("seed", seed_s.as_str())])
        .send()
        .await
        .map_err(|e| e.to_string())?;
    let status = resp.status();
    let text = resp.text().await.unwrap_or_default();
    if !status.is_success() {
        return Err(format!("HTTP {}: {}", status.as_u16(), text));
    }
    Ok(text)
}

/// Type a search string into whatever window currently has focus — used to drive the in-game
/// passive-tree search during an auto-sweep. The contributor clicks the search box once (so PoE2
/// holds keyboard focus); the click-through, no-activate overlay never steals it, so these
/// synthetic keystrokes land in the game. First clears the field (Ctrl+A then Delete), then types
/// `text` as Unicode (KEYEVENTF_UNICODE) so arbitrary characters — apostrophes in names like
/// "Mercenary's Lot" — type correctly regardless of keyboard layout. The whole sequence is one
/// SendInput batch (atomic w.r.t. other input). NOTE: this is opt-in (an explicit sweep hotkey),
/// never automatic — the contributor must focus the search box first or the keystrokes hit the game.
#[tauri::command]
fn type_search(text: String) -> Result<(), String> {
    use windows::Win32::UI::Input::KeyboardAndMouse::{
        SendInput, INPUT, INPUT_0, INPUT_KEYBOARD, KEYBDINPUT, KEYBD_EVENT_FLAGS, KEYEVENTF_KEYUP,
        KEYEVENTF_UNICODE, VIRTUAL_KEY, VK_A, VK_CONTROL, VK_DELETE,
    };
    fn vk(code: VIRTUAL_KEY, flags: KEYBD_EVENT_FLAGS) -> INPUT {
        INPUT {
            r#type: INPUT_KEYBOARD,
            Anonymous: INPUT_0 {
                ki: KEYBDINPUT { wVk: code, wScan: 0, dwFlags: flags, time: 0, dwExtraInfo: 0 },
            },
        }
    }
    fn unicode(unit: u16, up: bool) -> INPUT {
        let flags = if up { KEYEVENTF_UNICODE | KEYEVENTF_KEYUP } else { KEYEVENTF_UNICODE };
        INPUT {
            r#type: INPUT_KEYBOARD,
            Anonymous: INPUT_0 {
                ki: KEYBDINPUT { wVk: VIRTUAL_KEY(0), wScan: unit, dwFlags: flags, time: 0, dwExtraInfo: 0 },
            },
        }
    }
    let down = KEYBD_EVENT_FLAGS(0);
    let mut inputs: Vec<INPUT> = Vec::with_capacity(text.len() * 2 + 6);
    // Clear the field: Ctrl+A (select all) then Delete.
    inputs.push(vk(VK_CONTROL, down));
    inputs.push(vk(VK_A, down));
    inputs.push(vk(VK_A, KEYEVENTF_KEYUP));
    inputs.push(vk(VK_CONTROL, KEYEVENTF_KEYUP));
    inputs.push(vk(VK_DELETE, down));
    inputs.push(vk(VK_DELETE, KEYEVENTF_KEYUP));
    // Type the text as UTF-16 code units (down+up per unit).
    for u in text.encode_utf16() {
        inputs.push(unicode(u, false));
        inputs.push(unicode(u, true));
    }
    let sent = unsafe { SendInput(&inputs, std::mem::size_of::<INPUT>() as i32) };
    if sent as usize != inputs.len() {
        return Err(format!(
            "SendInput delivered {sent}/{} events — input may be blocked (run PoE2 and the overlay at the same privilege level).",
            inputs.len()
        ));
    }
    Ok(())
}

/// Copy the recorded transforms (serialised by the frontend) to the OS clipboard so the
/// contributor can paste a submission-ready batch. Uses arboard (already a dependency)
/// because the click-through overlay window can't reach navigator.clipboard.
#[tauri::command]
fn export_records(json: String) -> Result<(), String> {
    let mut cb = arboard::Clipboard::new().map_err(|e| e.to_string())?;
    cb.set_text(json).map_err(|e| e.to_string())?;
    Ok(())
}

/// Command form of `save_debug_capture` — invoked from the webview AFTER it has hidden the
/// overlay's own drawing, so the dumped frame shows only the game (no overlay markers polluting
/// the search-highlight signal). Returns the saved PNG path.
#[tauri::command]
fn save_capture() -> Result<String, String> {
    save_debug_capture()
}

/// Debug: save a raw primary-monitor capture to a PNG so detection masks can be
/// tuned against the user's real graphics settings. Returns the saved path. Each call writes a
/// fresh, incrementing filename (poe2_capture_0.png, _1.png, …) so successive dumps DON'T overwrite
/// each other — letting a contributor capture a matched set (e.g. a no-search baseline then a
/// search-highlight frame) for the maintainer to diff.
fn save_debug_capture() -> Result<String, String> {
    use std::sync::atomic::{AtomicU32, Ordering};
    static SEQ: AtomicU32 = AtomicU32::new(0);
    let _guard = CAPTURE_LOCK.lock().map_err(|_| "capture lock poisoned")?;
    let monitors = xcap::Monitor::all().map_err(|e| e.to_string())?;
    let monitor = monitors
        .into_iter()
        .find(|m| m.is_primary())
        .ok_or("no primary monitor")?;
    let img = monitor.capture_image().map_err(|e| e.to_string())?;
    let n = SEQ.fetch_add(1, Ordering::Relaxed);
    let mut path = std::env::temp_dir();
    path.push(format!("poe2_capture_{n}.png"));
    img.save(&path).map_err(|e| e.to_string())?;
    Ok(path.to_string_lossy().to_string())
}

/// Tray menu items we mutate at runtime — the show/hide entry's label flips with the window's
/// visibility ("Hide overlay" while shown, "Show overlay" while parked in the tray). Managed as
/// app state so both the tray-icon handlers and the JS-invoked commands can reach it.
struct TrayItems {
    toggle: MenuItem<tauri::Wry>,
}

/// Show or hide the transparent always-on-top draw layer and keep the tray's toggle label in
/// sync. Hiding parks the tool in the system tray without quitting; the tray icon (left-click or
/// "Show overlay") brings it back. The global hotkeys keep working while hidden, but nothing is
/// drawn until it's shown again.
fn set_overlay_visible(app: &tauri::AppHandle, visible: bool) {
    if let Some(win) = app.get_webview_window("main") {
        let _ = if visible { win.show() } else { win.hide() };
    }
    if let Some(items) = app.try_state::<TrayItems>() {
        let _ = items
            .toggle
            .set_text(if visible { "Hide overlay" } else { "Show overlay" });
    }
}

/// Flip the overlay between shown and hidden (tray left-click / "Show ⇄ Hide overlay" menu item).
fn toggle_overlay(app: &tauri::AppHandle) {
    let visible = app
        .get_webview_window("main")
        .and_then(|w| w.is_visible().ok())
        .unwrap_or(true);
    set_overlay_visible(app, !visible);
}

/// Hide the overlay to the system tray — the panel drop-down's "Hide to tray". Restore it from
/// the tray icon. Distinct from quitting: the process keeps running so hotkeys stay registered.
#[tauri::command]
fn hide_window(app: tauri::AppHandle) {
    set_overlay_visible(&app, false);
}

/// Quit the whole app — the panel drop-down's "Quit" and the tray "Quit".
#[tauri::command]
fn quit_app(app: tauri::AppHandle) {
    app.exit(0);
}

fn main() {
    // Disable GPU compositing for the WebView2 surface — transparent layered
    // windows on Windows 11 intermittently crash on creation with hardware
    // compositing enabled. This is the standard remedy.
    std::env::set_var("WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS", "--disable-gpu");

    // Ctrl+Shift+X: start / stop recording the jewel (reads the jewel + detects its socket on
    // start). Ctrl+Shift+R: recalibrate the pose. Ctrl+Shift+[ ]: correct a wrong socket guess.
    // Ctrl+Shift+S: dump a debug screen capture.
    let toggle_key = Shortcut::new(Some(Modifiers::CONTROL | Modifiers::SHIFT), Code::KeyX);
    let recal_key = Shortcut::new(Some(Modifiers::CONTROL | Modifiers::SHIFT), Code::KeyR);
    let dump_key = Shortcut::new(Some(Modifiers::CONTROL | Modifiers::SHIFT), Code::KeyS);
    let prev_key = Shortcut::new(Some(Modifiers::CONTROL | Modifiers::SHIFT), Code::BracketLeft);
    let next_key = Shortcut::new(Some(Modifiers::CONTROL | Modifiers::SHIFT), Code::BracketRight);
    // Ctrl+Shift+G: glow probe — with a name already typed in the tree search, light up which
    // in-radius nodes the game is highlighting (manual / debug check of the detector).
    let glow_key = Shortcut::new(Some(Modifiers::CONTROL | Modifiers::SHIFT), Code::KeyG);
    // Ctrl+Shift+A: auto-sweep — type every result-notable name into the tree search in turn and
    // record which base nodes light up. The contributor focuses the search box first.
    let sweep_key = Shortcut::new(Some(Modifiers::CONTROL | Modifiers::SHIFT), Code::KeyA);
    // Ctrl+Shift+D: skip the hovered node — a desecrated transform whose default can't be read.
    let skip_key = Shortcut::new(Some(Modifiers::CONTROL | Modifiers::SHIFT), Code::KeyD);

    tauri::Builder::default()
        // Single-instance must be registered first: a second launch hands its args to this
        // callback (in the already-running process) instead of starting over — we just bring
        // the overlay back into view rather than letting a duplicate spawn.
        .plugin(tauri_plugin_single_instance::init(|app, _argv, _cwd| {
            set_overlay_visible(app, true);
        }))
        .plugin(
            tauri_plugin_global_shortcut::Builder::new()
                .with_handler(move |app, sc, event| {
                    if event.state() != ShortcutState::Pressed {
                        return;
                    }
                    if sc == &toggle_key {
                        let _ = app.emit("toggle-run", ());
                    } else if sc == &recal_key {
                        let _ = app.emit("recalibrate", ());
                    } else if sc == &dump_key {
                        // Let the webview hide its own overlay drawing first, then call
                        // save_capture — so the dumped frame is the clean game screen (no overlay
                        // markers polluting the search-highlight signal we're tuning against).
                        let _ = app.emit("request-dump", ());
                    } else if sc == &prev_key {
                        let _ = app.emit("socket-cycle", -1i32);
                    } else if sc == &next_key {
                        let _ = app.emit("socket-cycle", 1i32);
                    } else if sc == &glow_key {
                        let _ = app.emit("debug-glow", ());
                    } else if sc == &sweep_key {
                        let _ = app.emit("auto-sweep", ());
                    } else if sc == &skip_key {
                        let _ = app.emit("skip-node", ());
                    }
                })
                .build(),
        )
        .invoke_handler(tauri::generate_handler![
            capture_and_detect,
            detect_glow,
            type_search,
            save_capture,
            get_cursor,
            set_click_through,
            read_jewel,
            clipboard_seq,
            ocr_region,
            export_records,
            submit_observations,
            fetch_consensus,
            hide_window,
            quit_app
        ])
        .setup(move |app| {
            // --- system tray ---------------------------------------------------------------
            // The overlay window is transparent, borderless and skips the taskbar, so the tray
            // icon is its home: left-click toggles show/hide; the menu adds Recalibrate and Quit.
            let toggle_item =
                MenuItem::with_id(app, "toggle_overlay", "Hide overlay", true, None::<&str>)?;
            let recal_item = MenuItem::with_id(
                app,
                "recalibrate",
                "Recalibrate",
                true,
                Some("Ctrl+Shift+R"),
            )?;
            let quit_item = MenuItem::with_id(app, "quit", "Quit", true, None::<&str>)?;
            let tray_menu = Menu::with_items(
                app,
                &[
                    &toggle_item,
                    &PredefinedMenuItem::separator(app)?,
                    &recal_item,
                    &PredefinedMenuItem::separator(app)?,
                    &quit_item,
                ],
            )?;
            app.manage(TrayItems {
                toggle: toggle_item.clone(),
            });
            let _tray = TrayIconBuilder::with_id("overlay-tray")
                .tooltip("PoE2 Jewel Overlay")
                .icon(
                    app.default_window_icon()
                        .cloned()
                        .ok_or("no default window icon to use for the tray")?,
                )
                .menu(&tray_menu)
                // Left-click toggles visibility instead of opening the menu (set below).
                .show_menu_on_left_click(false)
                .on_menu_event(|app, event| match event.id.as_ref() {
                    "toggle_overlay" => toggle_overlay(app),
                    "recalibrate" => {
                        let _ = app.emit("recalibrate", ());
                    }
                    "quit" => app.exit(0),
                    _ => {}
                })
                .on_tray_icon_event(|tray, event| {
                    if let TrayIconEvent::Click {
                        button: MouseButton::Left,
                        button_state: MouseButtonState::Up,
                        ..
                    } = event
                    {
                        toggle_overlay(tray.app_handle());
                    }
                })
                .build(app)?;

            let gs = app.global_shortcut();
            gs.register(toggle_key)?;
            gs.register(recal_key)?;
            gs.register(dump_key)?;
            gs.register(prev_key)?;
            gs.register(next_key)?;
            gs.register(glow_key)?;
            gs.register(sweep_key)?;
            gs.register(skip_key)?;
            if let Some(win) = app.get_webview_window("main") {
                // Click-through by default: the overlay never intercepts input, so it can't
                // lock the screen or steal focus from the game. The frontend flips this off
                // briefly while the cursor is over the draggable status panel (see
                // set_click_through). We do NOT resize/move the window here — the transparent
                // layered window is created at its final size in tauri.conf.json, because
                // resizing a transparent window after creation crashes WebView2 on Windows.
                let _ = win.set_ignore_cursor_events(true);
                // No-activate: even when click-through is briefly off (panel drag), clicking
                // the overlay must not pull focus away from the borderless-fullscreen game.
                let _ = win.set_focusable(false);
            }
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
