// PoE2 jewel-capture overlay — on-demand calibration, always click-through.
//
// The overlay window never intercepts input (it can't lock the screen or steal focus).
// Detection (screen capture + socketed-graphic template match + tree-snap) runs ONLY when you
// calibrate — Ctrl+Shift+K to start, Ctrl+Shift+R to recalibrate — locking a fixed screen pose.
// Highlights are drawn from that pose and persist while you pan/zoom or a tooltip covers the
// jewel; when they drift off the nodes you recalibrate. This is cheap (no per-frame capture)
// and robust (occlusion/zoom can't break a held pose). All control is via global hotkeys:
//   Ctrl+Shift+K = show/hide · Ctrl+Shift+R = recalibrate · Ctrl+Shift+C = read jewel (seed)
//   Ctrl+Shift+E = export recorded transforms to clipboard · Ctrl+Shift+J = force/confirm
// Recording is hands-free: rest the cursor on a notable so its in-game tooltip appears and,
// after a short dwell, the overlay OCRs it (Windows.Media.Ocr), fuzzy-matches the result
// name against the jewel's vocabulary, and records the transform {seed, socket, base node →
// result notable}. High-confidence matches record automatically; borderline ones wait for a
// Ctrl+Shift+J to confirm. Ctrl+Shift+J also force-reads the hovered node on demand.

import { invoke } from '@tauri-apps/api/core';
import { listen } from '@tauri-apps/api/event';
import socketData from './poe2_sockets.json';
import vocabData from './poe2_vocab.json';
import {
  projectNotables,
  ringInCss,
  nearestNode,
  type Notable,
  type Socket,
  type SocketData,
  type ProjectedNode
} from './projection';
import { matchNotable, type Match, type OcrLine, type Vocab } from './match';

const data = socketData as SocketData;
// Result-notable vocabulary per jewel name (generated by scripts/extract_vocab.mjs).
const vocab = vocabData as Record<string, Vocab[]>;
// Sorted socket list for manual cycling. Auto-detect picks a starting guess; the
// user corrects with Ctrl+Shift+[ / ] while watching the highlights snap to nodes.
const socketList: Socket[] = [...data.sockets].sort((a, b) => a.y - b.y || a.x - b.x);
const indexById = new Map<number, number>(socketList.map((s, i) => [s.socketId, i]));
const posLabel = (s: Socket): string => {
  const v = s.y < -2500 ? 'top' : s.y > 2500 ? 'bottom' : 'mid';
  const h = s.x < -2500 ? 'left' : s.x > 2500 ? 'right' : 'centre';
  return `${v}-${h}`;
};

interface Detection {
  cx: number;
  cy: number;
  r: number;
  support: number;
  coverage: number;
  resid: number;
  frame_w: number;
  frame_h: number;
  jewel: string;
  /** Socketed-graphic template-match correlation (−1..1); how confidently the pose was found. */
  jewel_match: number;
  /** Matched studded-frame width in px — the stable scale ruler (r is derived from it). */
  gem: number;
  socket_id: number;
  socket_score: number;
  socket_second: number;
}

// Minimum match correlation to trust a frame. Below this the socketed graphic isn't at the
// detected centre (lost lock mid-pan, or nothing matched), so the frame is dropped and the
// last good pose held — this kills the "snaps way off then back" cycle.
const MATCH_FLOOR = 0.3;

// --- DOM ---
const app = document.getElementById('app')!;
app.innerHTML = `
  <div id="panel">
    <h1>PoE2 Jewel Overlay <span class="tag">calibrate</span></h1>
    <div id="detect" class="muted">Stopped. Press <b>Ctrl+Shift+K</b> to start.</div>
    <div id="jewel" class="muted">No jewel yet. Copy it in-game (<b>Ctrl+C</b>) — auto-detected.</div>
    <div id="status" class="muted"></div>
    <div id="progress" class="muted"></div>
    <div id="sync" class="muted"></div>
    <div id="hint" class="muted">Hover a node to auto-record · <b>Ctrl+Shift+N</b> new socket · <b>Ctrl+Shift+K</b> show/hide · <b>Ctrl+Shift+R</b> recalibrate · <b>Ctrl+Shift+J</b> force/confirm · <b>Ctrl+Shift+C</b> read jewel · <b>Ctrl+Shift+E</b> export</div>
  </div>
  <svg id="layer"></svg>
`;
const detectEl = document.getElementById('detect')!;
const jewelEl = document.getElementById('jewel')!;
const statusEl = document.getElementById('status')!;
const progressEl = document.getElementById('progress')!;
const syncEl = document.getElementById('sync')!;
const layer = document.getElementById('layer') as unknown as SVGSVGElement;

// --- state ---
// On-demand calibration model: detection (the expensive screen-capture + template match) runs
// ONLY when the user calibrates (Ctrl+Shift+K to start, Ctrl+Shift+R to recalibrate). It locks
// a fixed screen pose; highlights are drawn from that pose and persist while you pan/zoom or a
// tooltip covers the jewel. When the view has moved enough that highlights drift off the nodes,
// you recalibrate. A cheap cursor-only poll (no capture) keeps the hover indicator live.
let active = false; // overlay shown (between Ctrl+Shift+K on/off)
let hoverTimer: number | undefined;
let rendering = false; // re-entrancy guard for the cursor-poll render
let socketIdx = 0; // index into socketList (current socket being projected)
let manualOverride = false; // true once the user cycles (drives the [manual] label)
// Once a socket is committed (auto-identified on the first calibrate, or manually cycled) it is
// LOCKED: later recalibrations refresh only the pose for THIS socket and never re-identify.
// Socket-ID is unreliable when zoomed far out (tiny frame → noisy scale → central sockets'
// constellations look alike), so re-picking on every recalibrate would jump to a wrong socket.
let socketChosen = false;
// The locked screen pose from the last successful calibration (physical px + effective radius).
let lockedPose: { cx: number; cy: number; r: number } | null = null;
// On-screen notable highlight radius as a fraction of the ring radius (both scale
// with zoom). Tune to taste — larger = the ring hugs further outside the notable.
const NODE_RADIUS_FRAC = 0.045;
interface JewelInfo {
  jewel: string;
  seed: number;
  conqueror: string;
}
let jewelInfo: JewelInfo | null = null; // parsed from the jewel's Ctrl+C item text
let targetIdx = 0;
const socket = (): Socket => socketList[socketIdx];

// A recorded transform: which base node (in which socket, for which seed) became which
// result notable, with the OCR match confidence. Submission-ready (resultId is the DB
// vocab id); keyed seed:socket:baseSkill so multiple seeds/sockets accumulate until export.
interface RecordedTransform {
  jewel: string;
  conqueror: string;
  seed: number;
  socketId: number;
  baseSkill: number;
  /** String node id (DB tree_notables.node_id) — the identifier submitted as node_id. */
  nodeId: string;
  baseName: string;
  resultId: string;
  resultName: string;
  confidence: number;
  /** True once this observation has been accepted by the server. */
  synced: boolean;
}
const recorded = new Map<string, RecordedTransform>();
// Keyed by (seed, node) — NOT socket: a timeless jewel's transform for a node depends only
// on the seed, so a node shared by overlapping sockets is recorded once and shows as done in
// every socket (matches the DB's seed+node uniqueness). source_socket is kept as metadata.
const recordKey = (seed: number, skill: number): string => `${seed}:${skill}`;
const isRecorded = (skill: number): boolean =>
  !!jewelInfo && recorded.has(recordKey(jewelInfo.seed, skill));

// --- contribution sync ---
// Writes go to the Cloudflare Worker (which holds the DB credential); the overlay never
// touches the DB directly. The POST is made from the Rust side (reqwest) because the
// webview CSP blocks cross-origin fetch — see submit_observations in main.rs.
const WORKER_BASE = 'https://timeless-jewels-proxy.davidleeanderson1991.workers.dev';
const RECORDS_KEY = 'poe2_overlay_records';
const CLIENT_KEY = 'poe2_overlay_client_id';
// A stable anonymous contributor id so consensus can count distinct contributors and
// re-recording the same node overwrites our own vote (DB upserts on jewel/seed/node/client).
const clientId: string =
  localStorage.getItem(CLIENT_KEY) ??
  (() => {
    const id = crypto.randomUUID();
    localStorage.setItem(CLIENT_KEY, id);
    return id;
  })();
let syncing = false;

function saveRecords(): void {
  localStorage.setItem(RECORDS_KEY, JSON.stringify([...recorded.entries()]));
}
function loadRecords(): void {
  try {
    const raw = localStorage.getItem(RECORDS_KEY);
    if (!raw) return;
    // Re-key under the current scheme (recordKey from the stored value) so records saved
    // under an older key format still load and dedupe correctly.
    for (const [, v] of JSON.parse(raw) as [string, RecordedTransform][]) {
      recorded.set(recordKey(v.seed, v.baseSkill), v);
    }
  } catch {
    /* corrupt store — start fresh */
  }
}
const pendingSync = (): number => {
  let n = 0;
  for (const r of recorded.values()) if (!r.synced) n++;
  return n;
};

// Push every not-yet-synced observation to the Worker in one batched POST. Idempotent
// upserts make retries safe; rows the server accepts are marked synced and persisted.
// Network/server failures leave records pending for the next flush (no data loss).
async function flushSync(): Promise<void> {
  if (syncing) return;
  const batch = [...recorded.entries()].filter(([, r]) => !r.synced);
  if (batch.length === 0) return;
  syncing = true;
  try {
    const observations = batch.map(([, r]) => ({
      jewel_type: r.jewel,
      conqueror: r.conqueror || null,
      seed: r.seed,
      node_id: r.nodeId,
      result_notable_id: r.resultId,
      source_socket: r.socketId
    }));
    const body = JSON.stringify({ client_id: clientId, observations });
    await invoke('submit_observations', { workerUrl: WORKER_BASE, body });
    // Server accepted (FK-valid + upserted). Mark this batch synced.
    for (const [, r] of batch) r.synced = true;
    saveRecords();
  } catch (e) {
    setText(syncEl, `sync pending (${pendingSync()}) — ${e}`, 'warn');
  } finally {
    syncing = false;
    updateSyncStatus();
  }
}
function updateSyncStatus(): void {
  const total = recorded.size;
  const pending = pendingSync();
  syncEl.textContent = total === 0 ? '' : `synced ${total - pending}/${total}${pending ? ` · ${pending} pending` : ''}`;
  syncEl.className = pending ? 'warn' : 'ok';
}

// OCR crop box (physical px) centred on the cursor — generous so the tooltip is captured
// whichever side of the node it flips to; the match is disambiguated by proximity.
const OCR_BOX_W = 1400;
const OCR_BOX_H = 1200;
// Confidence tiers: auto-record at/above ACCEPT, ask to confirm down to CONFIRM, reject below.
const ACCEPT = 0.92;
const CONFIRM = 0.75;
// A borderline match awaiting a Ctrl+Shift+J to accept, with the node it was matched on.
let pendingConfirm: { key: string; match: Match; node: Notable } | null = null;
const jewelVocab = (): Vocab[] => (jewelInfo ? (vocab[jewelInfo.jewel] ?? []) : []);

// --- hover auto-record ---
// Resting the cursor on a notable (so its in-game tooltip is up) for DWELL_MS auto-OCRs and
// records it — no keypress. Ctrl+Shift+J stays as a manual force / borderline-confirm.
const DWELL_MS = 450; // hover this long before auto-reading (tooltip needs to be visible)
let lastHover: ProjectedNode | null = null; // most recent hovered node (for the manual key)
let hoverSkill: number | null = null; // skill currently under the cursor
let hoverStart = 0; // when the cursor settled on hoverSkill (Date.now)
let autoTriedSkill: number | null = null; // node already auto-attempted this dwell (don't spam)
let autoTries = 0; // attempts on the current node — capped so a bad node can't loop OCR
const AUTO_MAX_TRIES = 3;
let ocrBusy = false; // an OCR pass (manual or auto) is in flight — serialise captures

function setText(el: Element, msg: string, kind: 'ok' | 'warn' | 'muted' = 'muted') {
  el.textContent = msg;
  el.className = kind === 'muted' ? 'muted' : kind;
}
function recordedHere(): number {
  const s = socket();
  return s.notables.reduce((n, x) => n + (isRecorded(x.skill) ? 1 : 0), 0);
}
function updateProgress() {
  if (active && lockedPose) {
    const s = socket();
    progressEl.textContent =
      `Socket ${socketIdx + 1}/${socketList.length} (${s.id} · ${posLabel(s)})` +
      `${manualOverride ? ' [manual]' : ''} · target ${Math.min(targetIdx + 1, s.notables.length)}/${s.notables.length} · recorded ${recordedHere()}/${s.notables.length}` +
      ` · Ctrl+Shift+[ ] to change`;
  } else {
    progressEl.textContent = '';
  }
}

// --- SVG ---
const NS = 'http://www.w3.org/2000/svg';
function clearLayer() {
  while (layer.firstChild) layer.removeChild(layer.firstChild);
}
function circle(cx: number, cy: number, r: number, cls: string) {
  const c = document.createElementNS(NS, 'circle');
  c.setAttribute('cx', String(cx));
  c.setAttribute('cy', String(cy));
  c.setAttribute('r', String(r));
  c.setAttribute('class', cls);
  layer.appendChild(c);
}
function label(x: number, y: number, text: string, cls: string) {
  const t = document.createElementNS(NS, 'text');
  t.setAttribute('x', String(x));
  t.setAttribute('y', String(y));
  t.setAttribute('class', cls);
  t.textContent = text;
  layer.appendChild(t);
}

function draw(
  projected: ProjectedNode[],
  ringCss: { cx: number; cy: number; r: number },
  hover: ProjectedNode | null
) {
  clearLayer();
  circle(ringCss.cx, ringCss.cy, ringCss.r, 'ring');
  // Highlight radius scales with the ring (zoom) so it hugs the notable icon at any
  // zoom — the notable's on-screen size is a fixed fraction of the ring radius.
  const nodeR = Math.max(7, ringCss.r * NODE_RADIUS_FRAC);
  const targetR = nodeR * 1.25;
  const target = projected[targetIdx];
  // While hovering a node its in-game tooltip is open (and we're about to auto-record it) —
  // show ONLY that node so the other circles/labels don't overlap the tooltip.
  if (hover) {
    const done = isRecorded(hover.notable.skill);
    circle(hover.sx, hover.sy, nodeR * 1.15, done ? 'node done' : 'hover');
    label(hover.sx + nodeR + 6, hover.sy + nodeR + 10, hover.notable.name, 'hoverLabel');
    return;
  }
  projected.forEach((p, i) => {
    const isTarget = i === targetIdx;
    const cls = isTarget ? 'node target' : isRecorded(p.notable.skill) ? 'node done' : 'node';
    circle(p.sx, p.sy, isTarget ? targetR : nodeR, cls);
  });
  if (target) label(target.sx + targetR + 6, target.sy - targetR, `→ ${target.notable.name}`, 'targetLabel');
}

// Render the locked pose's notables (optionally with a cursor hover indicator). Cheap and
// pure: reads only the held pose + the chosen socket, no screen capture.
function renderLocked(cursorPhysical?: { x: number; y: number }): ProjectedNode | null {
  if (!lockedPose) return null;
  const dpr = window.devicePixelRatio || 1;
  const ring = { ...lockedPose, support: 0, frame_w: 0, frame_h: 0 };
  const projected = projectNotables(ring, socket(), data.rTree, dpr);
  const hover = cursorPhysical
    ? nearestNode(projected, cursorPhysical, dpr, (lockedPose.r / dpr) * 0.14)
    : null;
  draw(projected, ringInCss(ring, dpr), hover);
  updateProgress();
  return hover;
}

function selectSocket(idx: number) {
  socketIdx = ((idx % socketList.length) + socketList.length) % socketList.length;
  pendingConfirm = null;
  resetTargetToFirstUnrecorded();
}

// Point the target at the first not-yet-recorded notable in the current socket (or the
// last if all are done), so recording resumes where it left off after a socket/seed switch.
function resetTargetToFirstUnrecorded() {
  const s = socket();
  let i = 0;
  while (i < s.notables.length && isRecorded(s.notables[i].skill)) i++;
  targetIdx = Math.min(i, Math.max(s.notables.length - 1, 0));
}

// --- calibration (the ONLY screen-capture path) ---
// One full detection: capture, locate the socketed graphic full-screen, identify the socket,
// and snap the pose to the tree. Locks `lockedPose`. On failure the previous pose is kept so a
// bad calibrate (tooltip over the jewel, too zoomed) never wipes a working overlay.
async function calibrate(): Promise<void> {
  if (!active) return;
  setText(detectEl, 'Calibrating…', 'muted');
  let det: Detection | null = null;
  try {
    det = (await invoke('capture_and_detect', {
      jewel: jewelInfo?.jewel ?? null,
      // Once a socket is locked, snap the pose to THAT socket and skip (unreliable) re-ID.
      // Only the first calibrate (nothing chosen yet) auto-identifies the socket.
      socketHint: socketChosen ? socket().socketId : null,
      identify: true
    })) as Detection | null;
  } catch (e) {
    setText(detectEl, `capture error: ${e}`, 'warn');
    return;
  }
  if (!det || det.jewel_match < MATCH_FLOOR) {
    setText(
      detectEl,
      'Could not find the socket. Centre it, zoom so the gold socket frame is clear, move any tooltip off it, then recalibrate (Ctrl+Shift+R).',
      'warn'
    );
    return; // keep any existing lockedPose
  }
  lockedPose = { cx: det.cx, cy: det.cy, r: det.r };
  // Adopt the auto-identified socket ONLY on the first calibrate (nothing chosen yet); after
  // that the socket is locked and recalibration just refreshes the pose for it.
  if (!socketChosen && det.socket_id >= 0 && indexById.has(det.socket_id)) {
    socketIdx = indexById.get(det.socket_id)!;
    targetIdx = 0;
    socketChosen = true;
  }
  const sock = socketChosen
    ? ` · socket ${socketIdx + 1}/${socketList.length}`
    : ' · socket unsure (cycle with Ctrl+Shift+[ ])';
  setText(detectEl, `Locked: ${det.jewel} · ${(det.jewel_match * 100) | 0}%${sock}`, 'ok');
  setText(
    statusEl,
    'Highlights locked. Pan/zoom or open tooltips freely; press Ctrl+Shift+R to recalibrate when they drift.',
    'muted'
  );
  renderLocked();
}

// Cheap cursor-only poll (NO screen capture) so the hover indicator follows the mouse while
// the locked pose stays put. Re-entrancy-guarded; self-reschedules while active.
async function hoverTick(): Promise<void> {
  if (!active) return;
  if (lockedPose && !rendering) {
    rendering = true;
    try {
      const cur = (await invoke('get_cursor')) as { x: number; y: number };
      lastHover = renderLocked(cur);
      maybeAutoRecord(lastHover);
    } catch {
      /* cursor unavailable this tick */
    } finally {
      rendering = false;
    }
  }
  if (active) hoverTimer = window.setTimeout(hoverTick, 120);
}

// Auto-record the node the cursor is resting on once its tooltip has had time to appear.
// Tracks dwell per node so we OCR a node at most once per hover (re-hover to retry); the
// OCR itself runs in recordNode, serialised by ocrBusy.
function maybeAutoRecord(hover: ProjectedNode | null): void {
  const skill = hover?.notable.skill ?? null;
  if (skill !== hoverSkill) {
    hoverSkill = skill;
    hoverStart = Date.now();
    autoTriedSkill = null;
    autoTries = 0;
    // Moving off the node abandons an unconfirmed borderline match.
    if (pendingConfirm && (skill === null || pendingConfirm.node.skill !== skill)) {
      pendingConfirm = null;
    }
  }
  if (!hover || skill === null) return;
  if (ocrBusy || autoTriedSkill === skill || isRecorded(skill)) return;
  if (Date.now() - hoverStart < DWELL_MS) return;
  autoTriedSkill = skill; // attempted this dwell — recordNode may reschedule a retry
  autoTries++;
  if (!jewelInfo) {
    setText(jewelEl, 'Read the jewel first (Ctrl+Shift+C) — recordings are keyed by seed.', 'warn');
    return;
  }
  void recordNode(hover, false);
}

function start() {
  active = true;
  manualOverride = false;
  socketChosen = false;
  lockedPose = null;
  void calibrate();
  void hoverTick();
}
function stop() {
  active = false;
  if (hoverTimer) window.clearTimeout(hoverTimer);
  lockedPose = null;
  pendingConfirm = null;
  clearLayer();
  setText(detectEl, 'Stopped. Press Ctrl+Shift+K to start.', 'muted');
  setText(statusEl, '');
  updateProgress();
}

// --- hotkeys (global, from Rust) ---
listen('toggle-run', () => (active ? stop() : start()));
listen('recalibrate', () => {
  if (active) void calibrate();
});
// Ctrl+Shift+N: the jewel was moved to a new socket. Unlock the socket and recalibrate so
// it auto-identifies the new one fresh (normal recalibrate keeps the locked socket). The seed
// is unchanged, so already-recorded nodes (incl. ones shared with the previous socket) stay
// recorded and show as done.
listen('next-socket', () => {
  if (active) void newSocket();
});
async function newSocket(): Promise<void> {
  socketChosen = false;
  manualOverride = false;
  pendingConfirm = null;
  setText(statusEl, 'Moved jewel — detecting the new socket… (centre it and zoom so the gold frame is clear)', 'muted');
  await calibrate();
  resetTargetToFirstUnrecorded();
  renderLocked();
}
listen<number>('socket-cycle', (e) => {
  if (!active) return;
  manualOverride = true;
  socketChosen = true; // lock to the user's pick; recalibrate refines the pose for it
  selectSocket(socketIdx + (e.payload < 0 ? -1 : 1));
  renderLocked();
});
listen('capture-hotkey', () => void recordCurrent());

// Ctrl+Shift+J: manual fallback. Accepts a pending borderline match if there is one,
// otherwise force-reads the node currently under the cursor (e.g. to re-record or to
// grab one before the auto dwell fires).
async function recordCurrent(): Promise<void> {
  if (!active || !lockedPose) return;
  if (pendingConfirm) {
    commitRecord(pendingConfirm.node, pendingConfirm.match);
    pendingConfirm = null;
    return;
  }
  if (!jewelInfo) {
    setText(jewelEl, 'Read the jewel first (Ctrl+Shift+C) — recordings are keyed by seed.', 'warn');
    return;
  }
  if (!lastHover) {
    setText(statusEl, 'Hover the node you want to record (its tooltip should be showing).', 'warn');
    return;
  }
  await recordNode(lastHover, true);
}

// OCR the tooltip near the cursor and record what the given node became. `manual` (the
// keypress path) surfaces failures and bypasses the already-recorded guard; the auto
// (hover) path stays quiet and reschedules a retry so a slightly-late tooltip still lands.
async function recordNode(p: ProjectedNode, manual: boolean): Promise<void> {
  if (!active || !lockedPose || !jewelInfo || ocrBusy) return;
  const node = p.notable;
  if (isRecorded(node.skill) && !manual) return;
  const key = recordKey(jewelInfo.seed, node.skill);
  ocrBusy = true;
  try {
    const dpr = window.devicePixelRatio || 1;
    const targetPhysical = { x: p.sx * dpr, y: p.sy * dpr };
    const cur = (await invoke('get_cursor')) as { x: number; y: number };
    const lines = (await invoke('ocr_region', {
      cx: cur.x,
      cy: cur.y,
      w: OCR_BOX_W,
      h: OCR_BOX_H
    })) as OcrLine[];
    const m = matchNotable(lines, jewelVocab(), targetPhysical);
    if (!m || m.confidence < CONFIRM) {
      if (manual) {
        setText(statusEl, `No confident match for ${node.name}. Make sure its tooltip is visible.`, 'warn');
      } else if (autoTries < AUTO_MAX_TRIES) {
        // Tooltip probably wasn't up yet — let the dwell retry this node shortly.
        autoTriedSkill = null;
        hoverStart = Date.now();
      }
      return;
    }
    if (m.confidence >= ACCEPT) {
      commitRecord(node, m);
    } else {
      pendingConfirm = { key, match: m, node };
      setText(
        statusEl,
        `Matched “${m.name}” (${Math.round(m.confidence * 100)}%) on ${node.name} — Ctrl+Shift+J to accept.`,
        'warn'
      );
    }
  } catch (e) {
    if (manual) setText(statusEl, `OCR error: ${e}`, 'warn');
  } finally {
    ocrBusy = false;
  }
}

function commitRecord(target: Notable, m: Match): void {
  if (!jewelInfo) return;
  const s = socket();
  recorded.set(recordKey(jewelInfo.seed, target.skill), {
    jewel: jewelInfo.jewel,
    conqueror: jewelInfo.conqueror,
    seed: jewelInfo.seed,
    socketId: s.socketId,
    baseSkill: target.skill,
    nodeId: target.id,
    baseName: target.name,
    resultId: m.id,
    resultName: m.name,
    confidence: m.confidence,
    synced: false
  });
  saveRecords();
  setText(statusEl, `Recorded: ${target.name} → ${m.name} (${Math.round(m.confidence * 100)}%)`, 'ok');
  // Advance to the next not-yet-recorded notable.
  let next = targetIdx + 1;
  while (next < s.notables.length && isRecorded(s.notables[next].skill)) next++;
  targetIdx = next;
  if (recordedHere() >= s.notables.length) {
    setText(
      statusEl,
      `Socket ${socketIdx + 1}/${socketList.length} complete — move the jewel to the next socket and press Ctrl+Shift+N.`,
      'ok'
    );
  }
  void flushSync();
  renderLocked();
}

// Ctrl+Shift+E: copy all recorded transforms to the clipboard (submission-ready JSON).
listen('export-records', () => void exportRecords());
async function exportRecords(): Promise<void> {
  if (recorded.size === 0) {
    setText(statusEl, 'Nothing recorded yet — hover a transformed notable so its tooltip shows.', 'warn');
    return;
  }
  const payload = [...recorded.values()];
  try {
    await invoke('export_records', { json: JSON.stringify(payload, null, 2) });
    setText(statusEl, `Exported ${payload.length} transform(s) to clipboard.`, 'ok');
  } catch (e) {
    setText(statusEl, `Export error: ${e}`, 'warn');
  }
}

// Jewel/seed capture from the clipboard. The seed is required for recording (the
// same node transforms differently per seed). The user copies the jewel in-game with
// Ctrl+C (a single natural action); we AUTO-POLL the clipboard so a new/swapped jewel
// is picked up within ~1s with no second hotkey. Ctrl+Shift+C forces an immediate
// read (and gives feedback when the clipboard isn't a jewel).
async function readJewelFromClipboard(verbose: boolean): Promise<void> {
  try {
    const info = (await invoke('read_jewel')) as JewelInfo | null;
    if (!info) {
      if (verbose)
        setText(jewelEl, 'No timeless jewel on clipboard — hover it and press Ctrl+C first.', 'warn');
      return;
    }
    const conq = info.conqueror ? ` · ${info.conqueror}` : '';
    if (jewelInfo && info.jewel === jewelInfo.jewel && info.seed === jewelInfo.seed) {
      if (verbose) setText(jewelEl, `Jewel: ${info.jewel} · seed ${info.seed}${conq} (unchanged)`, 'ok');
      return;
    }
    jewelInfo = info;
    setText(jewelEl, `Jewel: ${info.jewel} · seed ${info.seed}${conq}`, 'ok');
    // A new jewel/seed is a different recording set (records are keyed by seed). Keep the
    // existing records — they accumulate across seeds for a single batch export — and just
    // resume the walk at the first unrecorded notable for this seed.
    pendingConfirm = null;
    resetTargetToFirstUnrecorded();
    updateProgress();
  } catch (e) {
    if (verbose) setText(jewelEl, `clipboard error: ${e}`, 'warn');
  }
}
listen('read-jewel', () => void readJewelFromClipboard(true));
// Auto-poll: pick up a copied/swapped jewel without needing the hotkey.
setInterval(() => void readJewelFromClipboard(false), 1200);

// Debug: Ctrl+Shift+S dumps a raw screen capture for mask tuning.
listen<string>('debug-capture', (e) => {
  setText(statusEl, `Saved: ${e.payload}`, e.payload.startsWith('ERROR') ? 'warn' : 'ok');
});

setText(detectEl, 'Stopped. Ctrl+Shift+K to start · Ctrl+Shift+R recalibrate · Ctrl+Shift+S dump frame.', 'muted');

// Restore any records from a previous run and start the background sync: retry pending
// observations every few seconds (idempotent upserts), so a flaky network self-heals.
loadRecords();
updateSyncStatus();
setInterval(() => void flushSync(), 5000);
