// PoE2 jewel-capture overlay — one-button recording, always click-through.
//
// The overlay window never intercepts input (it can't lock the screen or steal focus).
// ONE hotkey drives everything: Ctrl+Shift+K — "Start recording jewel" reads the jewel from
// the clipboard (for the seed), detects the socket it's plugged into, and begins recording;
// pressing it again stops. Recording is hands-free: rest the cursor on a notable so its in-game
// tooltip appears and, after a short dwell, the overlay OCRs it (Windows.Media.Ocr), fuzzy-
// matches the result name against the jewel's vocabulary, and records {seed, socket, base node
// → result notable}, syncing in the background. When every notable in the socket is captured it
// auto-finishes ("Jewel successfully recorded") and returns to idle — move the jewel to the next
// socket and press Ctrl+Shift+K again to detect and record it.
// Helpers: Ctrl+Shift+R recalibrate the pose · Ctrl+Shift+[ ] correct a wrong socket guess.

import { invoke } from '@tauri-apps/api/core';
import { listen } from '@tauri-apps/api/event';
import socketData from './poe2_sockets.json';
import vocabData from './poe2_vocab.json';
import {
  projectNotables,
  ringInCss,
  nearestNode,
  type Notable,
  type Socket,
  type SocketData,
  type ProjectedNode
} from './projection';
import { matchNotable, type Match, type OcrLine, type Vocab } from './match';

const data = socketData as SocketData;
// Result-notable vocabulary per jewel name (generated by scripts/extract_vocab.mjs).
const vocab = vocabData as Record<string, Vocab[]>;
// Sorted socket list for manual cycling. Auto-detect picks a starting guess; the
// user corrects with Ctrl+Shift+[ / ] while watching the highlights snap to nodes.
const socketList: Socket[] = [...data.sockets].sort((a, b) => a.y - b.y || a.x - b.x);
const indexById = new Map<number, number>(socketList.map((s, i) => [s.socketId, i]));
const posLabel = (s: Socket): string => {
  const v = s.y < -2500 ? 'top' : s.y > 2500 ? 'bottom' : 'mid';
  const h = s.x < -2500 ? 'left' : s.x > 2500 ? 'right' : 'centre';
  return `${v}-${h}`;
};

interface Detection {
  cx: number;
  cy: number;
  r: number;
  support: number;
  coverage: number;
  resid: number;
  frame_w: number;
  frame_h: number;
  jewel: string;
  /** Socketed-graphic template-match correlation (−1..1); how confidently the pose was found. */
  jewel_match: number;
  /** Matched studded-frame width in px — the stable scale ruler (r is derived from it). */
  gem: number;
  socket_id: number;
  socket_score: number;
  socket_second: number;
}

// Minimum match correlation to trust a frame. Below this the socketed graphic isn't at the
// detected centre (lost lock mid-pan, or nothing matched), so the frame is dropped and the
// last good pose held — this kills the "snaps way off then back" cycle.
const MATCH_FLOOR = 0.3;

// --- DOM ---
const app = document.getElementById('app')!;
app.innerHTML = `
  <div id="panel">
    <div id="mode" class="mode">▶ Start recording jewel <span class="key">Ctrl+Shift+K</span></div>
    <div id="detect" class="muted">Copy the jewel in-game (Ctrl+C), then press Ctrl+Shift+K.</div>
    <div id="jewel" class="muted"></div>
    <div id="dbinfo" class="muted"></div>
    <div id="status" class="muted"></div>
    <div id="progress" class="muted"></div>
    <div id="sync" class="muted"></div>
    <div id="hint" class="muted">
      <div>Hover a node to auto-record it</div>
      <div><b>Ctrl+Shift+R</b> recalibrate · <b>Ctrl+Shift+[ ]</b> fix socket</div>
    </div>
  </div>
  <svg id="layer"></svg>
`;
const modeEl = document.getElementById('mode')!;
const detectEl = document.getElementById('detect')!;
const jewelEl = document.getElementById('jewel')!;
const dbInfoEl = document.getElementById('dbinfo')!;
const statusEl = document.getElementById('status')!;
const progressEl = document.getElementById('progress')!;
const syncEl = document.getElementById('sync')!;
const layer = document.getElementById('layer') as unknown as SVGSVGElement;
function updateModeLabel(): void {
  modeEl.innerHTML = active
    ? '■ Stop recording jewel <span class="key">Ctrl+Shift+K</span>'
    : '▶ Start recording jewel <span class="key">Ctrl+Shift+K</span>';
  modeEl.className = active ? 'mode recording' : 'mode';
}

// --- state ---
// On-demand calibration model: detection (the expensive screen-capture + template match) runs
// ONLY when the user calibrates (Ctrl+Shift+K to start, Ctrl+Shift+R to recalibrate). It locks
// a fixed screen pose; highlights are drawn from that pose and persist while you pan/zoom or a
// tooltip covers the jewel. When the view has moved enough that highlights drift off the nodes,
// you recalibrate. A cheap cursor-only poll (no capture) keeps the hover indicator live.
let active = false; // overlay shown (between Ctrl+Shift+K on/off)
let hoverTimer: number | undefined;
let rendering = false; // re-entrancy guard for the cursor-poll render
let socketIdx = 0; // index into socketList (current socket being projected)
let manualOverride = false; // true once the user cycles (drives the [manual] label)
// Once a socket is committed (auto-identified on the first calibrate, or manually cycled) it is
// LOCKED: later recalibrations refresh only the pose for THIS socket and never re-identify.
// Socket-ID is unreliable when zoomed far out (tiny frame → noisy scale → central sockets'
// constellations look alike), so re-picking on every recalibrate would jump to a wrong socket.
let socketChosen = false;
// The locked screen pose from the last successful calibration (physical px + effective radius).
let lockedPose: { cx: number; cy: number; r: number } | null = null;
// On-screen notable highlight radius as a fraction of the ring radius (both scale
// with zoom). Tune to taste — larger = the ring hugs further outside the notable.
const NODE_RADIUS_FRAC = 0.045;
interface JewelInfo {
  jewel: string;
  seed: number;
  conqueror: string;
}
let jewelInfo: JewelInfo | null = null; // parsed from the jewel's Ctrl+C item text
let targetIdx = 0;
const socket = (): Socket => socketList[socketIdx];

// A recorded transform: which base node (in which socket, for which seed) became which
// result notable, with the OCR match confidence. Submission-ready (resultId is the DB
// vocab id); keyed seed:socket:baseSkill so multiple seeds/sockets accumulate until export.
interface RecordedTransform {
  jewel: string;
  conqueror: string;
  seed: number;
  socketId: number;
  baseSkill: number;
  /** String node id (DB tree_notables.node_id) — the identifier submitted as node_id. */
  nodeId: string;
  baseName: string;
  resultId: string;
  resultName: string;
  confidence: number;
  /** True once this observation has been accepted by the server. */
  synced: boolean;
}
const recorded = new Map<string, RecordedTransform>();
// Keyed by (seed, node) — NOT socket: a timeless jewel's transform for a node depends only
// on the seed, so a node shared by overlapping sockets is recorded once and shows as done in
// every socket (matches the DB's seed+node uniqueness). source_socket is kept as metadata.
const recordKey = (seed: number, skill: number): string => `${seed}:${skill}`;
const isRecorded = (skill: number): boolean =>
  !!jewelInfo && recorded.has(recordKey(jewelInfo.seed, skill));

// Community consensus for the current seed, keyed by string node_id (tree_notables.node_id).
// Loaded from the Worker when a jewel is read, so the overlay can show what others already
// recorded and avoid redoing verified nodes.
let dbConsensus = new Map<string, { confirmations: number; verified: boolean }>();
// Track the fetch outcome so we never report "you're first" when we simply couldn't reach
// the DB (e.g. offline, or the overlay is running a build without the fetch_consensus command).
let dbState: 'idle' | 'loading' | 'loaded' | 'error' = 'idle';
let dbError = '';
const communityVerified = (n: Notable): boolean => dbConsensus.get(n.id)?.verified === true;
const communityPartial = (n: Notable): boolean => {
  const c = dbConsensus.get(n.id);
  return !!c && !c.verified;
};
// "Covered" = genuinely done, skip it: you recorded it this session, OR it's already verified
// (>=2 sources). A SINGLE unverified community record is NOT covered — it behaves like a fresh
// node (orange target, hover-focus, auto-record) so you can add the verifying 2nd source; the
// only difference is the "needs verify" annotation.
const isCovered = (n: Notable): boolean => isRecorded(n.skill) || communityVerified(n);

// Node name annotated with its community status, so it's clear at the point of recording
// whether someone already captured it (and whether that capture is verified yet).
function nodeLabel(n: Notable): string {
  if (isRecorded(n.skill)) return `${n.name} · recorded by you`;
  const c = dbConsensus.get(n.id);
  if (!c) return n.name;
  return c.verified ? `${n.name} · verified` : `${n.name} · recorded ×${c.confirmations}, needs verify`;
}

// --- contribution sync ---
// Writes go to the Cloudflare Worker (which holds the DB credential); the overlay never
// touches the DB directly. The POST is made from the Rust side (reqwest) because the
// webview CSP blocks cross-origin fetch — see submit_observations in main.rs.
const WORKER_BASE = 'https://timeless-jewels-proxy.davidleeanderson1991.workers.dev';
const RECORDS_KEY = 'poe2_overlay_records';
const CLIENT_KEY = 'poe2_overlay_client_id';
// A stable anonymous contributor id so consensus can count distinct contributors and
// re-recording the same node overwrites our own vote (DB upserts on jewel/seed/node/client).
const clientId: string =
  localStorage.getItem(CLIENT_KEY) ??
  (() => {
    const id = crypto.randomUUID();
    localStorage.setItem(CLIENT_KEY, id);
    return id;
  })();
let syncing = false;

function saveRecords(): void {
  localStorage.setItem(RECORDS_KEY, JSON.stringify([...recorded.entries()]));
}
function loadRecords(): void {
  try {
    const raw = localStorage.getItem(RECORDS_KEY);
    if (!raw) return;
    // Re-key under the current scheme (recordKey from the stored value) so records saved
    // under an older key format still load and dedupe correctly.
    for (const [, v] of JSON.parse(raw) as [string, RecordedTransform][]) {
      recorded.set(recordKey(v.seed, v.baseSkill), v);
    }
  } catch {
    /* corrupt store — start fresh */
  }
}
const pendingSync = (): number => {
  let n = 0;
  for (const r of recorded.values()) if (!r.synced) n++;
  return n;
};

// Push every not-yet-synced observation to the Worker in one batched POST. Idempotent
// upserts make retries safe; rows the server accepts are marked synced and persisted.
// Network/server failures leave records pending for the next flush (no data loss).
async function flushSync(): Promise<void> {
  if (syncing) return;
  const batch = [...recorded.entries()].filter(([, r]) => !r.synced);
  if (batch.length === 0) return;
  syncing = true;
  try {
    const observations = batch.map(([, r]) => ({
      jewel_type: r.jewel,
      conqueror: r.conqueror || null,
      seed: r.seed,
      node_id: r.nodeId,
      result_notable_id: r.resultId,
      source_socket: r.socketId
    }));
    const body = JSON.stringify({ client_id: clientId, observations });
    await invoke('submit_observations', { workerUrl: WORKER_BASE, body });
    // Server accepted (FK-valid + upserted). Mark this batch synced.
    for (const [, r] of batch) r.synced = true;
    saveRecords();
  } catch (e) {
    setText(syncEl, `sync pending (${pendingSync()}) — ${e}`, 'warn');
  } finally {
    syncing = false;
    updateSyncStatus();
  }
}
function updateSyncStatus(): void {
  const total = recorded.size;
  const pending = pendingSync();
  syncEl.textContent = total === 0 ? '' : `synced ${total - pending}/${total}${pending ? ` · ${pending} pending` : ''}`;
  syncEl.className = pending ? 'warn' : 'ok';
}

// Pull the community consensus for a (jewel, seed) so already-recorded nodes are shown and
// verified ones skipped — avoids redoing a jewel someone else already mapped. Best-effort:
// offline / not-found just leaves the map empty and recording proceeds as normal.
async function loadConsensus(jewel: string, seed: number): Promise<void> {
  dbConsensus = new Map();
  dbState = 'loading';
  dbError = '';
  updateDbInfo();
  try {
    const raw = (await invoke('fetch_consensus', { workerUrl: WORKER_BASE, jewel, seed })) as string;
    const data = JSON.parse(raw) as {
      results?: Array<{ node_id: string; confirmations: number; verified: boolean }>;
    };
    for (const r of data.results ?? []) {
      dbConsensus.set(r.node_id, { confirmations: r.confirmations, verified: r.verified });
    }
    dbState = 'loaded';
  } catch (e) {
    // DO NOT fall back to "you're first" — that would be a lie. Surface the real failure.
    dbState = 'error';
    dbError = String(e);
  }
  updateDbInfo();
  resetTargetToFirstUnrecorded();
  if (active && lockedPose) renderLocked();
}

function updateDbInfo(): void {
  if (!jewelInfo) {
    dbInfoEl.textContent = '';
    dbInfoEl.className = 'muted';
    return;
  }
  if (dbState === 'loading') {
    dbInfoEl.textContent = 'Checking community records…';
    dbInfoEl.className = 'muted';
    return;
  }
  if (dbState === 'error') {
    dbInfoEl.textContent = `Community DB unreachable — ${dbError} (records still save & retry).`;
    dbInfoEl.className = 'warn';
    return;
  }
  if (dbConsensus.size === 0) {
    dbInfoEl.textContent = 'Community: no records for this seed yet — you’re first.';
    dbInfoEl.className = 'community';
    return;
  }
  let verified = 0;
  for (const c of dbConsensus.values()) if (c.verified) verified++;
  const partial = dbConsensus.size - verified;
  // Lead with the unverified count — with sparse testing that's the common, important case.
  dbInfoEl.textContent =
    partial > 0
      ? `Community (seed ${jewelInfo.seed}): ${partial} recorded but UNVERIFIED (need a 2nd capture)` +
        `${verified ? `, ${verified} verified` : ''}.`
      : `Community (seed ${jewelInfo.seed}): all ${verified} verified.`;
  dbInfoEl.className = 'community';
}

// OCR crop box (physical px) centred on the cursor — generous so the tooltip is captured
// whichever side of the node it flips to; the match is disambiguated by proximity.
const OCR_BOX_W = 1400;
const OCR_BOX_H = 1200;
// Auto-record any match at or above this confidence; below it, retry the dwell then move on.
const ACCEPT = 0.75;
const jewelVocab = (): Vocab[] => (jewelInfo ? (vocab[jewelInfo.jewel] ?? []) : []);

// --- hover auto-record ---
// Resting the cursor on a notable (so its in-game tooltip is up) for DWELL_MS auto-OCRs and
// records it — no keypress.
const DWELL_MS = 450; // hover this long before auto-reading (tooltip needs to be visible)
let lastHover: ProjectedNode | null = null; // most recent hovered node
let hoverSkill: number | null = null; // skill currently under the cursor
let hoverStart = 0; // when the cursor settled on hoverSkill (Date.now)
let autoTriedSkill: number | null = null; // node already auto-attempted this dwell (don't spam)
let autoTries = 0; // attempts on the current node — capped so a bad node can't loop OCR
const AUTO_MAX_TRIES = 3;
let ocrBusy = false; // an OCR pass is in flight — serialise captures
let cycleTimer: number | undefined; // debounce the pose-refine after socket cycling

function setText(el: Element, msg: string, kind: 'ok' | 'warn' | 'muted' = 'muted') {
  el.textContent = msg;
  el.className = kind === 'muted' ? 'muted' : kind;
}
// How many of the current socket's notables are covered (recorded by you OR community-verified).
function coveredHere(): number {
  const s = socket();
  return s.notables.reduce((n, x) => n + (isCovered(x) ? 1 : 0), 0);
}
function updateProgress() {
  if (active && lockedPose) {
    const s = socket();
    progressEl.textContent =
      `Socket ${socketIdx + 1}/${socketList.length} (${s.id} · ${posLabel(s)})` +
      `${manualOverride ? ' [manual]' : ''} · ${coveredHere()}/${s.notables.length} done` +
      ` · Ctrl+Shift+[ ] to change`;
  } else {
    progressEl.textContent = '';
  }
}

// --- SVG ---
const NS = 'http://www.w3.org/2000/svg';
function clearLayer() {
  while (layer.firstChild) layer.removeChild(layer.firstChild);
}
function circle(cx: number, cy: number, r: number, cls: string) {
  const c = document.createElementNS(NS, 'circle');
  c.setAttribute('cx', String(cx));
  c.setAttribute('cy', String(cy));
  c.setAttribute('r', String(r));
  c.setAttribute('class', cls);
  layer.appendChild(c);
}
function label(x: number, y: number, text: string, cls: string) {
  const t = document.createElementNS(NS, 'text');
  t.setAttribute('x', String(x));
  t.setAttribute('y', String(y));
  t.setAttribute('class', cls);
  t.textContent = text;
  layer.appendChild(t);
}

function draw(
  projected: ProjectedNode[],
  ringCss: { cx: number; cy: number; r: number },
  hover: ProjectedNode | null
) {
  clearLayer();
  circle(ringCss.cx, ringCss.cy, ringCss.r, 'ring');
  // Highlight radius scales with the ring (zoom) so it hugs the notable icon at any
  // zoom — the notable's on-screen size is a fixed fraction of the ring radius.
  const nodeR = Math.max(7, ringCss.r * NODE_RADIUS_FRAC);
  const targetR = nodeR * 1.25;
  const target = projected[targetIdx];
  // While hovering an UNRECORDED node its in-game tooltip is open (and we're about to
  // auto-record it) — show ONLY that node so the other circles/labels don't overlap the
  // tooltip. Once it's recorded, fall through to draw everything again so the next node to
  // capture is immediately visible.
  if (hover && !isCovered(hover.notable)) {
    circle(hover.sx, hover.sy, nodeR * 1.15, 'hover');
    label(hover.sx + nodeR + 6, hover.sy + nodeR + 10, nodeLabel(hover.notable), 'hoverLabel');
    return;
  }
  projected.forEach((p, i) => {
    const n = p.notable;
    const isTarget = i === targetIdx;
    // Precedence: your record (green) > community-verified (violet, skip) > target (orange)
    // > community single-confirmation (violet dashed, still record) > to-do (white).
    let cls: string;
    if (isRecorded(n.skill)) cls = 'node done';
    else if (communityVerified(n)) cls = 'node community';
    else if (isTarget) cls = 'node target';
    else if (communityPartial(n)) cls = 'node partial';
    else cls = 'node';
    circle(p.sx, p.sy, isTarget ? targetR : nodeR, cls);
  });
  if (target) label(target.sx + targetR + 6, target.sy - targetR, `→ ${nodeLabel(target.notable)}`, 'targetLabel');
}

// Render the locked pose's notables (optionally with a cursor hover indicator). Cheap and
// pure: reads only the held pose + the chosen socket, no screen capture.
function renderLocked(cursorPhysical?: { x: number; y: number }): ProjectedNode | null {
  if (!lockedPose) return null;
  const dpr = window.devicePixelRatio || 1;
  const ring = { ...lockedPose, support: 0, frame_w: 0, frame_h: 0 };
  const projected = projectNotables(ring, socket(), data.rTree, dpr);
  const hover = cursorPhysical
    ? nearestNode(projected, cursorPhysical, dpr, (lockedPose.r / dpr) * 0.14)
    : null;
  draw(projected, ringInCss(ring, dpr), hover);
  updateProgress();
  return hover;
}

function selectSocket(idx: number) {
  socketIdx = ((idx % socketList.length) + socketList.length) % socketList.length;
  resetTargetToFirstUnrecorded();
}

// Point the target at the first not-yet-covered notable (you haven't recorded it and the
// community hasn't verified it), so recording resumes where it's actually needed.
function resetTargetToFirstUnrecorded() {
  const s = socket();
  let i = 0;
  while (i < s.notables.length && isCovered(s.notables[i])) i++;
  targetIdx = Math.min(i, Math.max(s.notables.length - 1, 0));
}

// --- calibration (the ONLY screen-capture path) ---
// One full detection: capture, locate the socketed graphic full-screen, identify the socket,
// and snap the pose to the tree. Locks `lockedPose`. On failure the previous pose is kept so a
// bad calibrate (tooltip over the jewel, too zoomed) never wipes a working overlay.
async function calibrate(): Promise<void> {
  if (!active) return;
  setText(detectEl, 'Detecting the jewel socket…', 'muted');
  let det: Detection | null = null;
  try {
    det = (await invoke('capture_and_detect', {
      jewel: jewelInfo?.jewel ?? null,
      // Once a socket is locked, snap the pose to THAT socket and skip (unreliable) re-ID.
      // Only the first calibrate (nothing chosen yet) auto-identifies the socket.
      socketHint: socketChosen ? socket().socketId : null,
      identify: true
    })) as Detection | null;
  } catch (e) {
    setText(detectEl, `capture error: ${e}`, 'warn');
    return;
  }
  if (!det || det.jewel_match < MATCH_FLOOR) {
    setText(
      detectEl,
      'Could not find the socket. Centre it, zoom so the gold socket frame is clear, move any tooltip off it, then recalibrate (Ctrl+Shift+R).',
      'warn'
    );
    return; // keep any existing lockedPose
  }
  lockedPose = { cx: det.cx, cy: det.cy, r: det.r };
  // Adopt the auto-identified socket ONLY on the first calibrate (nothing chosen yet); after
  // that the socket is locked and recalibration just refreshes the pose for it.
  if (!socketChosen && det.socket_id >= 0 && indexById.has(det.socket_id)) {
    socketIdx = indexById.get(det.socket_id)!;
    targetIdx = 0;
    socketChosen = true;
  }
  const sock = socketChosen
    ? ` · socket ${socketIdx + 1}/${socketList.length}`
    : ' · socket unsure (cycle with Ctrl+Shift+[ ])';
  setText(detectEl, `Locked: ${det.jewel} · ${(det.jewel_match * 100) | 0}%${sock}`, 'ok');
  setText(
    statusEl,
    'Highlights locked. Pan/zoom or open tooltips freely; press Ctrl+Shift+R to recalibrate when they drift.',
    'muted'
  );
  renderLocked();
}

// Cheap cursor-only poll (NO screen capture) so the hover indicator follows the mouse while
// the locked pose stays put. Re-entrancy-guarded; self-reschedules while active.
async function hoverTick(): Promise<void> {
  if (!active) return;
  if (lockedPose && !rendering) {
    rendering = true;
    try {
      const cur = (await invoke('get_cursor')) as { x: number; y: number };
      lastHover = renderLocked(cur);
      maybeAutoRecord(lastHover);
    } catch {
      /* cursor unavailable this tick */
    } finally {
      rendering = false;
    }
  }
  if (active) hoverTimer = window.setTimeout(hoverTick, 120);
}

// Auto-record the node the cursor is resting on once its tooltip has had time to appear.
// Tracks dwell per node so we OCR a node at most once per hover (re-hover to retry); the
// OCR itself runs in recordNode, serialised by ocrBusy.
function maybeAutoRecord(hover: ProjectedNode | null): void {
  const skill = hover?.notable.skill ?? null;
  if (skill !== hoverSkill) {
    hoverSkill = skill;
    hoverStart = Date.now();
    autoTriedSkill = null;
    autoTries = 0;
  }
  if (!hover || skill === null || !jewelInfo) return;
  if (ocrBusy || autoTriedSkill === skill || isCovered(hover.notable)) return;
  if (Date.now() - hoverStart < DWELL_MS) return;
  autoTriedSkill = skill; // attempted this dwell — recordNode may reschedule a retry
  autoTries++;
  void recordNode(hover);
}

// Ctrl+Shift+K (idle): start recording. Reads the jewel from the clipboard for the seed, then
// detects the socket it's plugged into and begins. Pressing K while recording stops.
async function startRecording(): Promise<void> {
  await readJewelFromClipboard(false); // pick up the jewel/seed from the clipboard
  if (!jewelInfo) {
    setText(detectEl, 'No jewel on the clipboard — copy it in-game (Ctrl+C), then press Ctrl+Shift+K.', 'warn');
    return; // stay idle
  }
  active = true;
  manualOverride = false;
  socketChosen = false; // fresh socket detection each start — this is how a moved jewel is handled
  lockedPose = null;
  hoverSkill = null;
  updateModeLabel();
  void calibrate();
  void hoverTick();
}

function stopRecording(message: string, kind: 'ok' | 'muted' = 'muted'): void {
  active = false;
  if (hoverTimer) window.clearTimeout(hoverTimer);
  if (cycleTimer) window.clearTimeout(cycleTimer);
  lockedPose = null;
  clearLayer();
  updateModeLabel();
  setText(detectEl, 'Copy the jewel in-game (Ctrl+C), then press Ctrl+Shift+K.', 'muted');
  setText(statusEl, message, kind);
  updateProgress();
}

// --- hotkeys (global, from Rust) ---
listen('toggle-run', () => {
  if (active) stopRecording('Recording stopped.');
  else void startRecording();
});
listen('recalibrate', () => {
  if (active) void calibrate();
});
listen<number>('socket-cycle', (e) => {
  if (!active) return;
  manualOverride = true;
  socketChosen = true; // lock to the user's pick
  selectSocket(socketIdx + (e.payload < 0 ? -1 : 1));
  renderLocked();
  // Snap the pose to the socket you land on, debounced so rapid cycling only captures once.
  if (cycleTimer) window.clearTimeout(cycleTimer);
  cycleTimer = window.setTimeout(() => void calibrate(), 350);
});

// OCR the tooltip near the cursor and record what the hovered node became. Auto path only:
// quiet on failure, and reschedules a dwell retry so a slightly-late tooltip still lands.
async function recordNode(p: ProjectedNode): Promise<void> {
  if (!active || !lockedPose || !jewelInfo || ocrBusy) return;
  const node = p.notable;
  if (isCovered(node)) return;
  ocrBusy = true;
  try {
    const dpr = window.devicePixelRatio || 1;
    const targetPhysical = { x: p.sx * dpr, y: p.sy * dpr };
    const cur = (await invoke('get_cursor')) as { x: number; y: number };
    const lines = (await invoke('ocr_region', {
      cx: cur.x,
      cy: cur.y,
      w: OCR_BOX_W,
      h: OCR_BOX_H
    })) as OcrLine[];
    const m = matchNotable(lines, jewelVocab(), targetPhysical);
    if (m && m.confidence >= ACCEPT) {
      commitRecord(node, m);
    } else if (autoTries < AUTO_MAX_TRIES) {
      // Tooltip probably wasn't up yet — let the dwell retry this node shortly.
      autoTriedSkill = null;
      hoverStart = Date.now();
    }
  } catch {
    /* OCR failed this tick — ignore (the dwell may retry) */
  } finally {
    ocrBusy = false;
  }
}

function commitRecord(target: Notable, m: Match): void {
  if (!jewelInfo) return;
  const s = socket();
  recorded.set(recordKey(jewelInfo.seed, target.skill), {
    jewel: jewelInfo.jewel,
    conqueror: jewelInfo.conqueror,
    seed: jewelInfo.seed,
    socketId: s.socketId,
    baseSkill: target.skill,
    nodeId: target.id,
    baseName: target.name,
    resultId: m.id,
    resultName: m.name,
    confidence: m.confidence,
    synced: false
  });
  saveRecords();
  setText(statusEl, `Recorded: ${target.name} → ${m.name} (${Math.round(m.confidence * 100)}%)`, 'ok');
  // Advance to the next not-yet-covered notable.
  let next = targetIdx + 1;
  while (next < s.notables.length && isCovered(s.notables[next])) next++;
  targetIdx = next;
  void flushSync();
  if (coveredHere() >= s.notables.length) {
    void completeSocket();
  } else {
    renderLocked();
  }
}

// Every notable in this socket is captured: flush the last records to the DB, then finish —
// stop recording and return to idle so you can move the jewel and start the next socket.
async function completeSocket(): Promise<void> {
  await flushSync();
  stopRecording(
    'Jewel successfully recorded ✓ — move the jewel to the next socket and press Ctrl+Shift+K.',
    'ok'
  );
}

// Jewel/seed capture from the clipboard. The seed is required for recording (the same node
// transforms differently per seed). The user copies the jewel in-game with Ctrl+C; we read it
// on Start and also AUTO-POLL so a swapped jewel is picked up within ~1s.
async function readJewelFromClipboard(verbose: boolean): Promise<void> {
  try {
    const info = (await invoke('read_jewel')) as JewelInfo | null;
    if (!info) {
      if (verbose)
        setText(jewelEl, 'No timeless jewel on clipboard — hover it and press Ctrl+C first.', 'warn');
      return;
    }
    const conq = info.conqueror ? ` · ${info.conqueror}` : '';
    if (jewelInfo && info.jewel === jewelInfo.jewel && info.seed === jewelInfo.seed) {
      if (verbose) setText(jewelEl, `Jewel: ${info.jewel} · seed ${info.seed}${conq} (unchanged)`, 'ok');
      return;
    }
    jewelInfo = info;
    setText(jewelEl, `Jewel: ${info.jewel} · seed ${info.seed}${conq}`, 'ok');
    // A new jewel/seed is a different recording set (records are keyed by seed). Keep the
    // existing records and just resume the walk at the first unrecorded notable for this seed.
    resetTargetToFirstUnrecorded();
    updateProgress();
    // Pull what the community already has for this seed (verified nodes get skipped).
    void loadConsensus(info.jewel, info.seed);
  } catch (e) {
    if (verbose) setText(jewelEl, `clipboard error: ${e}`, 'warn');
  }
}
// Auto-poll: pick up a copied/swapped jewel without needing a hotkey.
setInterval(() => void readJewelFromClipboard(false), 1200);

// Debug: Ctrl+Shift+S dumps a raw screen capture for mask tuning.
listen<string>('debug-capture', (e) => {
  setText(statusEl, `Saved: ${e.payload}`, e.payload.startsWith('ERROR') ? 'warn' : 'ok');
});

setText(detectEl, 'Copy the jewel in-game (Ctrl+C), then press Ctrl+Shift+K to start.', 'muted');

// Restore any records from a previous run and start the background sync: retry pending
// observations every few seconds (idempotent upserts), so a flaky network self-heals.
loadRecords();
updateSyncStatus();
setInterval(() => void flushSync(), 5000);
