// PoE2 jewel-capture overlay — one-button recording, always click-through.
//
// The overlay window never intercepts input (it can't lock the screen or steal focus).
// ONE hotkey drives everything: Ctrl+Shift+X — "Start recording jewel" reads the jewel from
// the clipboard (for the seed), detects the socket it's plugged into, and begins recording;
// pressing it again stops. Recording is hands-free: rest the cursor on a notable so its in-game
// tooltip appears and, after a short dwell, the overlay OCRs it (Windows.Media.Ocr), fuzzy-
// matches the result name against the jewel's vocabulary, and records {seed, socket, base node
// → result notable}, syncing in the background. When every notable in the socket is captured it
// auto-finishes ("Jewel successfully recorded") and returns to idle — move the jewel to the next
// socket and press Ctrl+Shift+X again to detect and record it.
// Helpers: Ctrl+Shift+R recalibrate the pose · Ctrl+Shift+[ ] correct a wrong socket guess.

import { invoke } from '@tauri-apps/api/core';
import { listen } from '@tauri-apps/api/event';
import socketData from './poe2_sockets.json';
import vocabData from './poe2_vocab.json';
import {
  projectNotables,
  ringInCss,
  nearestNode,
  orderNotablesNearest,
  type Notable,
  type Socket,
  type SocketData,
  type ProjectedNode
} from './projection';
import { matchNotable, type Match, type OcrLine, type Vocab } from './match';

const data = socketData as SocketData;
// Result-notable vocabulary per jewel name (generated by scripts/extract_vocab.mjs).
const vocab = vocabData as Record<string, Vocab[]>;
// Sorted socket list for manual cycling. Auto-detect picks a starting guess; the
// user corrects with Ctrl+Shift+[ / ] while watching the highlights snap to nodes.
const socketList: Socket[] = [...data.sockets]
  .map((s) => ({ ...s, notables: orderNotablesNearest(s) }))
  .sort((a, b) => a.y - b.y || a.x - b.x);
const indexById = new Map<number, number>(socketList.map((s, i) => [s.socketId, i]));
const posLabel = (s: Socket): string => {
  const v = s.y < -2500 ? 'top' : s.y > 2500 ? 'bottom' : 'mid';
  const h = s.x < -2500 ? 'left' : s.x > 2500 ? 'right' : 'centre';
  return `${v}-${h}`;
};

interface Detection {
  cx: number;
  cy: number;
  r: number;
  support: number;
  coverage: number;
  resid: number;
  frame_w: number;
  frame_h: number;
  jewel: string;
  /** Socketed-graphic template-match correlation (−1..1); how confidently the pose was found. */
  jewel_match: number;
  /** Matched studded-frame width in px — the stable scale ruler (r is derived from it). */
  gem: number;
  socket_id: number;
  socket_score: number;
  socket_second: number;
  /** Colour ring missing but the white hover-highlight ring is present — the jewel is being
   * hovered (tooltip up). Move the cursor off it and re-detect. */
  hovered: boolean;
}

// Minimum match correlation to trust a frame. Below this the socketed graphic isn't at the
// detected centre (lost lock mid-pan, or nothing matched), so the frame is dropped and the
// last good pose held — this kills the "snaps way off then back" cycle.
const MATCH_FLOOR = 0.3;

// --- DOM ---
const app = document.getElementById('app')!;
app.innerHTML = `
  <div id="panel">
    <div id="mode" class="mode">▶ Start recording jewel <span class="key">Ctrl+Shift+X</span></div>
    <div id="detect" class="muted">Copy the jewel in-game (Ctrl+C), then press Ctrl+Shift+X.</div>
    <div id="jewel" class="muted"></div>
    <div id="dbinfo" class="muted"></div>
    <div id="status" class="muted"></div>
    <div id="progress" class="muted"></div>
    <div id="sync" class="muted"></div>
    <div id="hint" class="muted">
      <div>Hover a node to auto-record it</div>
      <div><b>Ctrl+Shift+R</b> recalibrate · <b>Ctrl+Shift+[ ]</b> fix socket</div>
    </div>
    <label id="oracleRow" class="oracle-row" title="Tick if your character is a Druid Oracle with The Unseen Path allocated — only then are the Oracle-only nodes capturable.">
      <input type="checkbox" id="oracleChk" /> Druid Oracle (Unseen Path)
    </label>
  </div>
  <svg id="layer"></svg>
  <div id="toast"></div>
`;
const modeEl = document.getElementById('mode')!;
const detectEl = document.getElementById('detect')!;
const jewelEl = document.getElementById('jewel')!;
const dbInfoEl = document.getElementById('dbinfo')!;
const statusEl = document.getElementById('status')!;
const progressEl = document.getElementById('progress')!;
const syncEl = document.getElementById('sync')!;
const toastEl = document.getElementById('toast')!;
const panelEl = document.getElementById('panel')!;
const layer = document.getElementById('layer') as unknown as SVGSVGElement;

// --- draggable status panel ---------------------------------------------------------------
// The overlay window is click-through (set_ignore_cursor_events), so the panel can only get
// mouse events while we flip click-through OFF. A cheap cursor poll flips it off whenever the
// OS cursor is over the panel (or a drag is in progress) and back on otherwise — the panel is
// the only interactive surface, everything else stays click-through so the game gets the input.
const PANEL_POS_KEY = 'poe2_overlay_panel_pos';
let dragging = false;
let dragDX = 0; // cursor-to-panel offset captured on mousedown (CSS px)
let dragDY = 0;
let clickThrough = true; // mirrors the OS state so we only invoke on a real change

function clampPanelToViewport(left: number, top: number): { left: number; top: number } {
  const r = panelEl.getBoundingClientRect();
  const maxLeft = Math.max(0, window.innerWidth - r.width);
  const maxTop = Math.max(0, window.innerHeight - r.height);
  return { left: Math.min(Math.max(0, left), maxLeft), top: Math.min(Math.max(0, top), maxTop) };
}
function applyPanelPos(left: number, top: number): void {
  const c = clampPanelToViewport(left, top);
  panelEl.style.left = `${c.left}px`;
  panelEl.style.top = `${c.top}px`;
  panelEl.style.right = 'auto'; // override the CSS default so left/top fully control position
}
function savePanelPos(): void {
  const r = panelEl.getBoundingClientRect();
  localStorage.setItem(PANEL_POS_KEY, JSON.stringify({ left: r.left, top: r.top }));
}
function restorePanelPos(): void {
  try {
    const raw = localStorage.getItem(PANEL_POS_KEY);
    if (!raw) return;
    const { left, top } = JSON.parse(raw) as { left: number; top: number };
    if (typeof left === 'number' && typeof top === 'number') applyPanelPos(left, top);
  } catch {
    /* corrupt store — keep the CSS default position */
  }
}

panelEl.addEventListener('mousedown', (e: MouseEvent) => {
  dragging = true;
  const r = panelEl.getBoundingClientRect();
  dragDX = e.clientX - r.left;
  dragDY = e.clientY - r.top;
  panelEl.classList.add('dragging');
  e.preventDefault();
});
window.addEventListener('mousemove', (e: MouseEvent) => {
  if (dragging) applyPanelPos(e.clientX - dragDX, e.clientY - dragDY);
});
window.addEventListener('mouseup', () => {
  if (!dragging) return;
  dragging = false;
  panelEl.classList.remove('dragging');
  savePanelPos();
});

// Poll the OS cursor and flip click-through so the panel is interactive only when needed.
// Runs always (idle too), independent of the recording hover loop. Cheap; ~60ms cadence.
async function clickThroughTick(): Promise<void> {
  try {
    const dpr = window.devicePixelRatio || 1;
    const cur = (await invoke('get_cursor')) as { x: number; y: number };
    const r = panelEl.getBoundingClientRect();
    const pad = 4;
    const x = cur.x / dpr;
    const y = cur.y / dpr;
    const overPanel =
      x >= r.left - pad && x <= r.right + pad && y >= r.top - pad && y <= r.bottom + pad;
    const wantClickThrough = !(overPanel || dragging);
    if (wantClickThrough !== clickThrough) {
      clickThrough = wantClickThrough;
      await invoke('set_click_through', { enabled: wantClickThrough });
    }
  } catch {
    /* cursor unavailable this tick — leave the current state */
  }
}
restorePanelPos();
setInterval(() => void clickThroughTick(), 60);

// Transient centre-screen notice (e.g. "Already captured by you.") that fades out after a few
// seconds. Independent of the panel's status lines so it can't be missed mid-game.
const TOAST_MS = 5000;
let toastTimer: number | undefined;
// Show the notice anchored just below a CSS point (the jewel, the focal point the user is
// already looking at). Without a point it falls back to screen centre.
function showToast(msg: string, at?: { x: number; y: number }): void {
  toastEl.textContent = msg;
  if (at) {
    toastEl.style.left = `${at.x}px`;
    toastEl.style.top = `${at.y}px`;
    toastEl.style.transform = 'translate(-50%, 0)'; // anchor is the toast's top-centre
  } else {
    toastEl.style.left = '50%';
    toastEl.style.top = '50%';
    toastEl.style.transform = 'translate(-50%, -50%)';
  }
  toastEl.classList.add('show');
  if (toastTimer) window.clearTimeout(toastTimer);
  toastTimer = window.setTimeout(() => toastEl.classList.remove('show'), TOAST_MS);
}

// CSS point just below the jewel socket — close enough to stay in the user's focus, but clear
// of the item tooltip (which opens above/beside the jewel). A small fixed drop from the socket
// centre, NOT the full ring radius, which would land it far down the tree.
const TOAST_DROP = 48;
function underJewelPoint(pose: { cx: number; cy: number; r: number }): { x: number; y: number } {
  const dpr = window.devicePixelRatio || 1;
  const css = ringInCss({ ...pose, support: 0, frame_w: 0, frame_h: 0 }, dpr);
  return { x: css.cx, y: css.cy + TOAST_DROP };
}
function updateModeLabel(): void {
  if (active) {
    modeEl.innerHTML = '■ Stop recording jewel <span class="key">Ctrl+Shift+X</span>';
    modeEl.className = 'mode recording';
  } else if (arming) {
    modeEl.innerHTML = '… Waiting for jewel — Ctrl+C it <span class="key">Ctrl+Shift+X</span> to cancel';
    modeEl.className = 'mode arming';
  } else {
    modeEl.innerHTML = '▶ Start recording jewel <span class="key">Ctrl+Shift+X</span>';
    modeEl.className = 'mode';
  }
}

// --- state ---
// On-demand calibration model: detection (the expensive screen-capture + template match) runs
// ONLY when the user calibrates (Ctrl+Shift+X to start, Ctrl+Shift+R to recalibrate). It locks
// a fixed screen pose; highlights are drawn from that pose and persist while you pan/zoom or a
// tooltip covers the jewel. When the view has moved enough that highlights drift off the nodes,
// you recalibrate. A cheap cursor-only poll (no capture) keeps the hover indicator live.
let active = false; // recording in progress (seed locked, hover auto-records)
// Arming handshake: Ctrl+Shift+X from idle enters this state and waits for the user to
// deliberately Ctrl+C the jewel before recording starts, so the active seed is always one
// the user just picked — never whatever happened to be on the clipboard.
let arming = false;
let armSeq = 0; // clipboard sequence number snapshotted when arming began
let armTimer: number | undefined; // poll that watches for the deliberate copy
let redetectTimer: number | undefined; // retries socket detection while arming until it locks
let hoverTimer: number | undefined;
let rendering = false; // re-entrancy guard for the cursor-poll render
let socketIdx = 0; // index into socketList (current socket being projected)
let manualOverride = false; // true once the user cycles (drives the [manual] label)
// Once a socket is committed (auto-identified on the first calibrate, or manually cycled) it is
// LOCKED: later recalibrations refresh only the pose for THIS socket and never re-identify.
// Socket-ID is unreliable when zoomed far out (tiny frame → noisy scale → central sockets'
// constellations look alike), so re-picking on every recalibrate would jump to a wrong socket.
let socketChosen = false;
// The locked screen pose from the last successful calibration (physical px + effective radius).
let lockedPose: { cx: number; cy: number; r: number } | null = null;
// On-screen notable highlight radius as a fraction of the ring radius (both scale
// with zoom). Tune to taste — larger = the ring hugs further outside the notable.
const NODE_RADIUS_FRAC = 0.045;
interface JewelInfo {
  jewel: string;
  seed: number;
  conqueror: string;
}
let jewelInfo: JewelInfo | null = null; // parsed from the jewel's Ctrl+C item text
let targetIdx = 0;
const socket = (): Socket => socketList[socketIdx];

// Whether the player is a Druid Oracle with "The Unseen Path" allocated. When false (the
// default — most characters aren't), the Oracle-only notables (oracleOnly) are skipped as
// capture targets and don't count toward socket completion, since the player can't allocate or
// hover them. Persisted across runs; toggled via the panel checkbox.
const ORACLE_KEY = 'poe2_overlay_is_oracle';
let isOraclePlayer = localStorage.getItem(ORACLE_KEY) === '1';

// A recorded transform: which base node (in which socket, for which seed) became which
// result notable, with the OCR match confidence. Submission-ready (resultId is the DB
// vocab id); keyed seed:socket:baseSkill so multiple seeds/sockets accumulate until export.
interface RecordedTransform {
  jewel: string;
  conqueror: string;
  seed: number;
  socketId: number;
  baseSkill: number;
  /** String node id (DB tree_notables.node_id) — the identifier submitted as node_id. */
  nodeId: string;
  baseName: string;
  resultId: string;
  resultName: string;
  confidence: number;
  /** True once this observation has been accepted by the server. */
  synced: boolean;
  /** Quarantined: the server permanently rejected this row (bad FK / seed out of
   *  range), so it's excluded from auto-retry to stop it blocking and spamming. */
  failed?: boolean;
}
const recorded = new Map<string, RecordedTransform>();
// Keyed by (seed, node) — NOT socket: a timeless jewel's transform for a node depends only
// on the seed, so a node shared by overlapping sockets is recorded once and shows as done in
// every socket (matches the DB's seed+node uniqueness). source_socket is kept as metadata.
const recordKey = (seed: number, skill: number): string => `${seed}:${skill}`;
const isRecorded = (skill: number): boolean =>
  !!jewelInfo && recorded.has(recordKey(jewelInfo.seed, skill));

// Community consensus for the current seed, keyed by string node_id (tree_notables.node_id).
// Loaded from the Worker when a jewel is read, so the overlay can show what others already
// recorded and avoid redoing verified nodes.
let dbConsensus = new Map<string, { confirmations: number; verified: boolean }>();
// Track the fetch outcome so we never report "you're first" when we simply couldn't reach
// the DB (e.g. offline, or the overlay is running a build without the fetch_consensus command).
let dbState: 'idle' | 'loading' | 'loaded' | 'error' = 'idle';
let dbError = '';
const communityVerified = (n: Notable): boolean => dbConsensus.get(n.id)?.verified === true;
const communityPartial = (n: Notable): boolean => {
  const c = dbConsensus.get(n.id);
  return !!c && !c.verified;
};
// "Covered" = genuinely done, skip it: you recorded it this session, OR it's already verified
// (>=2 sources). A SINGLE unverified community record is NOT covered — it behaves like a fresh
// node (orange target, hover-focus, auto-record) so you can add the verifying 2nd source; the
// only difference is the "needs verify" annotation.
const isCovered = (n: Notable): boolean => isRecorded(n.skill) || communityVerified(n);

// A node the current player can actually allocate. Oracle-only nodes (Unseen Path) aren't in a
// non-Oracle's tree, so they're not theirs to capture unless the player marks themselves an
// Oracle. Everything else is always reachable.
const reachable = (n: Notable): boolean => isOraclePlayer || !n.oracleOnly;
// Still needs capturing here: reachable by this player and not already covered.
const needsCapture = (n: Notable): boolean => reachable(n) && !isCovered(n);
// Notables in the current socket that this player can actually capture.
const reachableNotables = (): Notable[] => socket().notables.filter(reachable);

// Node name annotated with its community status, so it's clear at the point of recording
// whether someone already captured it (and whether that capture is verified yet).
function nodeLabel(n: Notable): string {
  if (isRecorded(n.skill)) return `${n.name} · recorded by you`;
  const c = dbConsensus.get(n.id);
  if (!c) return n.name;
  return c.verified ? `${n.name} · verified` : `${n.name} · recorded ×${c.confirmations}, needs verify`;
}

// --- contribution sync ---
// Writes go to the Cloudflare Worker (which holds the DB credential); the overlay never
// touches the DB directly. The POST is made from the Rust side (reqwest) because the
// webview CSP blocks cross-origin fetch — see submit_observations in main.rs.
const WORKER_BASE = 'https://timeless-jewels-proxy.davidleeanderson1991.workers.dev';
const RECORDS_KEY = 'poe2_overlay_records';
const CLIENT_KEY = 'poe2_overlay_client_id';
// A stable anonymous contributor id so consensus can count distinct contributors and
// re-recording the same node overwrites our own vote (DB upserts on jewel/seed/node/client).
const clientId: string =
  localStorage.getItem(CLIENT_KEY) ??
  (() => {
    const id = crypto.randomUUID();
    localStorage.setItem(CLIENT_KEY, id);
    return id;
  })();
let syncing = false;

function saveRecords(): void {
  localStorage.setItem(RECORDS_KEY, JSON.stringify([...recorded.entries()]));
}
function loadRecords(): void {
  try {
    const raw = localStorage.getItem(RECORDS_KEY);
    if (!raw) return;
    // Re-key under the current scheme (recordKey from the stored value) so records saved
    // under an older key format still load and dedupe correctly.
    for (const [, v] of JSON.parse(raw) as [string, RecordedTransform][]) {
      recorded.set(recordKey(v.seed, v.baseSkill), v);
    }
  } catch {
    /* corrupt store — start fresh */
  }
}
const pendingSync = (): number => {
  let n = 0;
  for (const r of recorded.values()) if (!r.synced && !r.failed) n++;
  return n;
};
const failedSync = (): number => {
  let n = 0;
  for (const r of recorded.values()) if (!r.synced && r.failed) n++;
  return n;
};

// Cap each POST well under the server's hourly budget so one flush can't trip the
// throttle in a single shot, and so a rejected batch only forces row-by-row retry
// over a small slice rather than the whole backlog.
const SYNC_CHUNK = 200;
// When the server reports its hourly limit, stop hammering it: pause all syncing for
// this long, then resume from where we left off (the window will have moved on).
const THROTTLE_BACKOFF_MS = 5 * 60 * 1000;
let backoffUntil = 0;

// The Worker surfaces the DB throttle (PT429) as "HTTP 400: …rate limit exceeded…".
const isThrottle = (msg: string): boolean => /rate limit|PT429|\b429\b/i.test(msg);

async function postObservations(batch: [string, RecordedTransform][]): Promise<void> {
  const observations = batch.map(([, r]) => ({
    jewel_type: r.jewel,
    conqueror: r.conqueror || null,
    seed: r.seed,
    node_id: r.nodeId,
    result_notable_id: r.resultId,
    source_socket: r.socketId
  }));
  const body = JSON.stringify({ client_id: clientId, observations });
  await invoke('submit_observations', { workerUrl: WORKER_BASE, body });
}

// Push not-yet-synced observations to the Worker in capped chunks. Idempotent upserts
// make retries safe. A whole chunk is one DB transaction that aborts if any single row
// is rejected, so on chunk failure we fall back to row-by-row: valid rows land and only
// genuinely-bad rows are quarantined (failed=true) instead of blocking the backlog
// forever. Throttle responses pause syncing rather than spin.
async function flushSync(): Promise<void> {
  if (syncing || Date.now() < backoffUntil) return;
  const pending = [...recorded.entries()].filter(([, r]) => !r.synced && !r.failed);
  if (pending.length === 0) return;
  syncing = true;
  try {
    for (let i = 0; i < pending.length; i += SYNC_CHUNK) {
      const chunk = pending.slice(i, i + SYNC_CHUNK);
      try {
        await postObservations(chunk);
        for (const [, r] of chunk) r.synced = true;
        saveRecords();
      } catch (e) {
        if (isThrottle(String(e))) {
          backoffUntil = Date.now() + THROTTLE_BACKOFF_MS;
          return; // resume on a later interval, once the hourly window has moved
        }
        // One bad row aborted the chunk's transaction. Retry each row alone so the
        // rest still sync and only the offender is quarantined.
        for (const entry of chunk) {
          try {
            await postObservations([entry]);
            entry[1].synced = true;
          } catch (e2) {
            if (isThrottle(String(e2))) {
              backoffUntil = Date.now() + THROTTLE_BACKOFF_MS;
              saveRecords();
              return;
            }
            entry[1].failed = true; // permanent rejection (bad FK / seed range)
            console.warn('observation rejected:', entry[1], String(e2));
          }
        }
        saveRecords();
      }
    }
  } finally {
    syncing = false;
    updateSyncStatus();
  }
}
function updateSyncStatus(): void {
  const total = recorded.size;
  if (total === 0) {
    syncEl.textContent = '';
    syncEl.className = 'ok';
    return;
  }
  const pending = pendingSync();
  const failed = failedSync();
  const parts = [`synced ${total - pending - failed}/${total}`];
  if (pending) parts.push(Date.now() < backoffUntil ? `${pending} pending (paused)` : `${pending} pending`);
  if (failed) parts.push(`${failed} rejected`);
  syncEl.textContent = parts.join(' · ');
  syncEl.className = pending || failed ? 'warn' : 'ok';
}

// Pull the community consensus for a (jewel, seed) so already-recorded nodes are shown and
// verified ones skipped — avoids redoing a jewel someone else already mapped. Best-effort:
// offline / not-found just leaves the map empty and recording proceeds as normal.
async function loadConsensus(jewel: string, seed: number): Promise<void> {
  dbConsensus = new Map();
  dbState = 'loading';
  dbError = '';
  updateDbInfo();
  try {
    const raw = (await invoke('fetch_consensus', { workerUrl: WORKER_BASE, jewel, seed })) as string;
    const data = JSON.parse(raw) as {
      results?: Array<{ node_id: string; confirmations: number; verified: boolean }>;
    };
    for (const r of data.results ?? []) {
      dbConsensus.set(r.node_id, { confirmations: r.confirmations, verified: r.verified });
    }
    dbState = 'loaded';
  } catch (e) {
    // DO NOT fall back to "you're first" — that would be a lie. Surface the real failure.
    dbState = 'error';
    dbError = String(e);
  }
  updateDbInfo();
  resetTargetToFirstUnrecorded();
  if (active && lockedPose) renderLocked();
}

function updateDbInfo(): void {
  if (!jewelInfo) {
    dbInfoEl.textContent = '';
    dbInfoEl.className = 'muted';
    return;
  }
  if (dbState === 'loading') {
    dbInfoEl.textContent = 'Checking community records…';
    dbInfoEl.className = 'muted';
    return;
  }
  if (dbState === 'error') {
    dbInfoEl.textContent = `Community DB unreachable — ${dbError} (records still save & retry).`;
    dbInfoEl.className = 'warn';
    return;
  }
  if (dbConsensus.size === 0) {
    dbInfoEl.textContent = 'Community: no records for this seed yet — you’re first.';
    dbInfoEl.className = 'community';
    return;
  }
  let verified = 0;
  for (const c of dbConsensus.values()) if (c.verified) verified++;
  const partial = dbConsensus.size - verified;
  // Lead with the unverified count — with sparse testing that's the common, important case.
  dbInfoEl.textContent =
    partial > 0
      ? `Community (seed ${jewelInfo.seed}): ${partial} recorded but UNVERIFIED (need a 2nd capture)` +
        `${verified ? `, ${verified} verified` : ''}.`
      : `Community (seed ${jewelInfo.seed}): all ${verified} verified.`;
  dbInfoEl.className = 'community';
}

// OCR crop box (physical px) centred on the cursor — generous so the tooltip is captured
// whichever side of the node it flips to; the match is disambiguated by proximity.
const OCR_BOX_W = 1400;
const OCR_BOX_H = 1200;
// Auto-record any match at or above this confidence; below it, retry the dwell then move on.
const ACCEPT = 0.75;
const jewelVocab = (): Vocab[] => (jewelInfo ? (vocab[jewelInfo.jewel] ?? []) : []);

// Drop OCR lines that sit over the status panel so its own text can't be matched as a notable.
// `lines` carry physical-px centres; the panel's getBoundingClientRect is CSS px, so we scale
// the line centre down by dpr before testing. A small pad covers the panel's soft shadow edge.
function linesOutsidePanel(lines: OcrLine[], dpr: number): OcrLine[] {
  const panel = document.getElementById('panel');
  if (!panel) return lines;
  const r = panel.getBoundingClientRect();
  const pad = 6;
  return lines.filter((l) => {
    const x = l.cx / dpr;
    const y = l.cy / dpr;
    return !(x >= r.left - pad && x <= r.right + pad && y >= r.top - pad && y <= r.bottom + pad);
  });
}

// --- hover auto-record ---
// Resting the cursor on a notable (so its in-game tooltip is up) for DWELL_MS auto-OCRs and
// records it — no keypress.
const DWELL_MS = 450; // hover this long before auto-reading (tooltip needs to be visible)
let lastHover: ProjectedNode | null = null; // most recent hovered node
let hoverSkill: number | null = null; // skill currently under the cursor
let hoverStart = 0; // when the cursor settled on hoverSkill (Date.now)
let autoTriedSkill: number | null = null; // node already auto-attempted this dwell (don't spam)
let autoTries = 0; // attempts on the current node — capped so a bad node can't loop OCR
const AUTO_MAX_TRIES = 3;
let ocrBusy = false; // an OCR pass is in flight — serialise captures
let cycleTimer: number | undefined; // debounce the pose-refine after socket cycling

function setText(el: Element, msg: string, kind: 'ok' | 'warn' | 'muted' = 'muted') {
  el.textContent = msg;
  el.className = kind === 'muted' ? 'muted' : kind;
}
// How many of the current socket's REACHABLE notables are covered (recorded by you OR
// community-verified). Oracle-only nodes a non-Oracle can't reach are excluded from both the
// count and the total, so the socket still completes for them.
function coveredHere(): number {
  return reachableNotables().reduce((n, x) => n + (isCovered(x) ? 1 : 0), 0);
}
// True when every notable in the current socket that this player can reach is already recorded
// by YOU for this seed — re-capturing this exact jewel would just paint the screen green.
function allRecordedByYouHere(): boolean {
  const r = reachableNotables();
  return r.length > 0 && r.every((n) => isRecorded(n.skill));
}
function updateProgress() {
  if (active && lockedPose) {
    const s = socket();
    progressEl.textContent =
      `Socket ${socketIdx + 1}/${socketList.length} (${s.id} · ${posLabel(s)})` +
      `${manualOverride ? ' [manual]' : ''} · ${coveredHere()}/${reachableNotables().length} done` +
      ` · Ctrl+Shift+[ ] to change`;
  } else {
    progressEl.textContent = '';
  }
}

// --- SVG ---
const NS = 'http://www.w3.org/2000/svg';
function clearLayer() {
  while (layer.firstChild) layer.removeChild(layer.firstChild);
}
function circle(cx: number, cy: number, r: number, cls: string) {
  const c = document.createElementNS(NS, 'circle');
  c.setAttribute('cx', String(cx));
  c.setAttribute('cy', String(cy));
  c.setAttribute('r', String(r));
  c.setAttribute('class', cls);
  layer.appendChild(c);
}
function label(x: number, y: number, text: string, cls: string) {
  const t = document.createElementNS(NS, 'text');
  t.setAttribute('x', String(x));
  t.setAttribute('y', String(y));
  t.setAttribute('class', cls);
  t.textContent = text;
  layer.appendChild(t);
}

function draw(
  projected: ProjectedNode[],
  ringCss: { cx: number; cy: number; r: number },
  hover: ProjectedNode | null
) {
  clearLayer();
  circle(ringCss.cx, ringCss.cy, ringCss.r, 'ring');
  // Highlight radius scales with the ring (zoom) so it hugs the notable icon at any
  // zoom — the notable's on-screen size is a fixed fraction of the ring radius.
  const nodeR = Math.max(7, ringCss.r * NODE_RADIUS_FRAC);
  const targetR = nodeR * 1.25;
  const target = projected[targetIdx];
  // While hovering an UNRECORDED node its in-game tooltip is open (and we're about to
  // auto-record it) — show ONLY that node so the other circles/labels don't overlap the
  // tooltip. Once it's recorded, fall through to draw everything again so the next node to
  // capture is immediately visible.
  if (hover && reachable(hover.notable) && !isCovered(hover.notable)) {
    circle(hover.sx, hover.sy, nodeR * 1.15, 'hover');
    label(hover.sx + nodeR + 6, hover.sy + nodeR + 10, nodeLabel(hover.notable), 'hoverLabel');
    return;
  }
  projected.forEach((p, i) => {
    const n = p.notable;
    if (!reachable(n)) return; // Oracle-only node, player isn't an Oracle — not theirs to capture
    const isTarget = i === targetIdx;
    // Precedence: your record (green) > community-verified (violet, skip) > target (orange)
    // > community single-confirmation (violet dashed, still record) > to-do (white).
    let cls: string;
    if (isRecorded(n.skill)) cls = 'node done';
    else if (communityVerified(n)) cls = 'node community';
    else if (isTarget) cls = 'node target';
    else if (communityPartial(n)) cls = 'node partial';
    else cls = 'node';
    circle(p.sx, p.sy, isTarget ? targetR : nodeR, cls);
  });
  if (target && reachable(target.notable))
    label(target.sx + targetR + 6, target.sy - targetR, `→ ${nodeLabel(target.notable)}`, 'targetLabel');
}

// Render the locked pose's notables (optionally with a cursor hover indicator). Cheap and
// pure: reads only the held pose + the chosen socket, no screen capture.
function renderLocked(cursorPhysical?: { x: number; y: number }): ProjectedNode | null {
  if (!lockedPose) return null;
  const dpr = window.devicePixelRatio || 1;
  const ring = { ...lockedPose, support: 0, frame_w: 0, frame_h: 0 };
  const projected = projectNotables(ring, socket(), data.rTree, dpr);
  // Only nodes the player can capture are hover candidates, so an Oracle-only node never steals
  // the hover focus for a non-Oracle (in-game that spot is empty for them).
  const hover = cursorPhysical
    ? nearestNode(projected.filter((p) => reachable(p.notable)), cursorPhysical, dpr, (lockedPose.r / dpr) * 0.14)
    : null;
  draw(projected, ringInCss(ring, dpr), hover);
  updateProgress();
  return hover;
}

function selectSocket(idx: number) {
  socketIdx = ((idx % socketList.length) + socketList.length) % socketList.length;
  resetTargetToFirstUnrecorded();
}

// Point the target at the first not-yet-covered notable (you haven't recorded it and the
// community hasn't verified it), so recording resumes where it's actually needed.
function resetTargetToFirstUnrecorded() {
  const s = socket();
  let i = 0;
  while (i < s.notables.length && !needsCapture(s.notables[i])) i++;
  targetIdx = Math.min(i, Math.max(s.notables.length - 1, 0));
}

// --- calibration (the ONLY screen-capture path) ---
// One full detection: capture, locate the socketed graphic full-screen, identify the socket,
// and snap the pose to the tree. Locks `lockedPose`. On failure the previous pose is kept so a
// bad calibrate (tooltip over the jewel, too zoomed) never wipes a working overlay.
async function calibrate(): Promise<void> {
  if (!active && !arming) return;
  setText(detectEl, 'Detecting the jewel socket…', 'muted');
  let det: Detection | null = null;
  try {
    det = (await invoke('capture_and_detect', {
      jewel: jewelInfo?.jewel ?? null,
      // Once a socket is locked, snap the pose to THAT socket and skip (unreliable) re-ID.
      // Only the first calibrate (nothing chosen yet) auto-identifies the socket.
      socketHint: socketChosen ? socket().socketId : null,
      identify: true
    })) as Detection | null;
  } catch (e) {
    setText(detectEl, `capture error: ${e}`, 'warn');
    return;
  }
  if (det?.hovered) {
    // White ring instead of the colour one: the jewel's tooltip is up, hiding the colour the
    // mask needs. Ask the user to move off it and auto-retry — no Ctrl+Shift+R dance.
    setText(detectEl, "You're hovering the jewel — move the cursor off it to detect the socket.", 'warn');
    setText(statusEl, 'Re-detecting automatically…', 'muted');
    drawHoverOffCue(det);
    if (arming) scheduleRedetect();
    return; // keep any existing lockedPose
  }
  if (!det || det.jewel_match < MATCH_FLOOR) {
    setText(
      detectEl,
      'Could not find the socket. Centre it, zoom so the gold socket frame is clear, move any tooltip off it, then recalibrate (Ctrl+Shift+R).',
      'warn'
    );
    if (arming) scheduleRedetect(); // self-heal once the view/zoom is fixed
    return; // keep any existing lockedPose
  }
  lockedPose = { cx: det.cx, cy: det.cy, r: det.r };
  // Adopt the auto-identified socket ONLY on the first calibrate (nothing chosen yet); after
  // that the socket is locked and recalibration just refreshes the pose for it.
  if (!socketChosen && det.socket_id >= 0 && indexById.has(det.socket_id)) {
    socketIdx = indexById.get(det.socket_id)!;
    targetIdx = 0;
    socketChosen = true;
  }
  const sock = socketChosen
    ? ` · socket ${socketIdx + 1}/${socketList.length}`
    : ' · socket unsure (cycle with Ctrl+Shift+[ ])';
  if (arming) {
    // Detected on a clean screen — now point the user at the jewel to copy it. No notable
    // overlay yet (the seed isn't known until the copy), just a cue on the jewel itself.
    setText(detectEl, `Socket locked${sock} — now hover the jewel and press Ctrl+C.`, 'ok');
    setText(statusEl, 'Copy the jewel (Ctrl+C) to capture its seed. Ctrl+Shift+R to re-detect.', 'muted');
    drawCopyCue();
    return;
  }
  setText(detectEl, `Locked: ${det.jewel} · ${(det.jewel_match * 100) | 0}%${sock}`, 'ok');
  setText(
    statusEl,
    'Highlights locked. Pan/zoom or open tooltips freely; press Ctrl+Shift+R to recalibrate when they drift.',
    'muted'
  );
  renderLocked();
}

// Arming visual: the detected ring, a small dot on the jewel, and a compact arrow-label beside
// it pointing at the jewel — not a banner over the radius. Mask-safe orange (see the
// .node.target note) so re-detecting with the cue on screen can't bias the ring fit.
function drawCopyCue(): void {
  if (!lockedPose) return;
  const dpr = window.devicePixelRatio || 1;
  const ring = { ...lockedPose, support: 0, frame_w: 0, frame_h: 0 };
  const css = ringInCss(ring, dpr);
  clearLayer();
  circle(css.cx, css.cy, css.r, 'ring');
  circle(css.cx, css.cy, 6, 'copyMarker'); // small dot marking the jewel itself
  // Label sits just to the right of the jewel; the leading arrow points back at it.
  label(css.cx + 14, css.cy + 4, '← Ctrl+C on jewel', 'copyLabel');
}

// Same compact style as the copy cue, but for the hovered state: a marker on the jewel (located
// via the white ring) and a "move off" prompt. Drawn from the white-ring pose, not lockedPose.
function drawHoverOffCue(det: Detection): void {
  const dpr = window.devicePixelRatio || 1;
  const css = ringInCss({ cx: det.cx, cy: det.cy, r: det.r, support: 0, frame_w: 0, frame_h: 0 }, dpr);
  clearLayer();
  circle(css.cx, css.cy, css.r, 'ring');
  circle(css.cx, css.cy, 6, 'copyMarker');
  label(css.cx + 14, css.cy + 4, '← move cursor off jewel', 'copyLabel');
}

// While arming, retry socket detection until it locks (e.g. once the user moves off the jewel,
// or re-centres the tree). Single pending timer; calibrate reschedules if it still fails.
const REDETECT_MS = 800;
function scheduleRedetect(): void {
  if (redetectTimer || !arming) return;
  redetectTimer = window.setTimeout(() => {
    redetectTimer = undefined;
    if (arming && !lockedPose) void calibrate();
  }, REDETECT_MS);
}
function clearRedetect(): void {
  if (redetectTimer) window.clearTimeout(redetectTimer);
  redetectTimer = undefined;
}

// Cheap cursor-only poll (NO screen capture) so the hover indicator follows the mouse while
// the locked pose stays put. Re-entrancy-guarded; self-reschedules while active.
async function hoverTick(): Promise<void> {
  if (!active) return;
  if (lockedPose && !rendering) {
    rendering = true;
    try {
      const cur = (await invoke('get_cursor')) as { x: number; y: number };
      lastHover = renderLocked(cur);
      maybeAutoRecord(lastHover);
    } catch {
      /* cursor unavailable this tick */
    } finally {
      rendering = false;
    }
  }
  if (active) hoverTimer = window.setTimeout(hoverTick, 120);
}

// Auto-record the node the cursor is resting on once its tooltip has had time to appear.
// Tracks dwell per node so we OCR a node at most once per hover (re-hover to retry); the
// OCR itself runs in recordNode, serialised by ocrBusy.
function maybeAutoRecord(hover: ProjectedNode | null): void {
  const skill = hover?.notable.skill ?? null;
  if (skill !== hoverSkill) {
    hoverSkill = skill;
    hoverStart = Date.now();
    autoTriedSkill = null;
    autoTries = 0;
  }
  if (!hover || skill === null || !jewelInfo) return;
  if (ocrBusy || autoTriedSkill === skill || !reachable(hover.notable) || isCovered(hover.notable)) return;
  if (Date.now() - hoverStart < DWELL_MS) return;
  autoTriedSkill = skill; // attempted this dwell — recordNode may reschedule a retry
  autoTries++;
  void recordNode(hover);
}

const ARM_POLL_MS = 300; // how often the arming poll checks for the deliberate Ctrl+C
const IDLE_PROMPT = 'Press Ctrl+Shift+X, then hover the jewel in-game and press Ctrl+C.';

// Ctrl+Shift+X (idle): ARM. Snapshot the clipboard's change counter and wait for the user to
// deliberately Ctrl+C the jewel — only THEN do we read the seed. This guarantees the recorded
// seed is the one the user just picked, never a stale jewel left on the clipboard. Recording
// does not start until a valid jewel is copied (see armTick → startActiveRecording).
async function beginArming(): Promise<void> {
  try {
    armSeq = (await invoke('clipboard_seq')) as number;
  } catch (e) {
    setText(detectEl, `clipboard error: ${e}`, 'warn');
    return; // stay idle
  }
  arming = true;
  // Fresh detection: forget any previous jewel/socket so calibrate detects the ring (either
  // colour) on the clean screen and auto-identifies the socket.
  jewelInfo = null;
  manualOverride = false;
  socketChosen = false;
  lockedPose = null;
  hoverSkill = null;
  clearLayer();
  updateModeLabel();
  // Detect the socket NOW, while no tooltip is up — the ring/tree are unoccluded. calibrate
  // (arming branch) draws the "Ctrl+C the jewel" cue on success.
  await calibrate();
  // Then wait for the deliberate copy. armSeq was snapshotted before calibrate, so a copy made
  // during detection is still caught on the first poll tick.
  if (armTimer) window.clearInterval(armTimer);
  armTimer = window.setInterval(() => void armTick(), ARM_POLL_MS);
}

// While arming: detect the deliberate copy via the clipboard change counter (bumps even when
// the re-copied text is identical), then parse it. A valid jewel locks the seed and starts
// recording; anything else leaves a hint and keeps waiting.
async function armTick(): Promise<void> {
  if (!arming) return;
  // Don't accept a copy until the socket is locked — otherwise a record could bind to an
  // unknown socket. (Copying requires hovering the jewel, which whitens the ring, so detection
  // must finish first.) Keep retrying detection until it locks; the copy is read once it does.
  if (!lockedPose) {
    scheduleRedetect();
    return;
  }
  let seq: number;
  try {
    seq = (await invoke('clipboard_seq')) as number;
  } catch {
    return; // transient — try again next tick
  }
  if (seq === armSeq) return; // nothing copied yet
  armSeq = seq; // consume this change whether or not it's a jewel
  const info = (await invoke('read_jewel').catch(() => null)) as JewelInfo | null;
  if (!info) {
    setText(detectEl, "That copy wasn't a timeless jewel — hover the jewel and press Ctrl+C.", 'warn');
    return; // keep waiting
  }
  bindJewel(info);
  startActiveRecording();
}

function cancelArming(message: string): void {
  arming = false;
  if (armTimer) window.clearInterval(armTimer);
  armTimer = undefined;
  clearRedetect();
  clearLayer(); // remove the copy cue
  updateModeLabel();
  setText(detectEl, IDLE_PROMPT, 'muted');
  setText(statusEl, message, 'muted');
}

// Seed is bound — start recording. The socket was already detected during arming on a clean
// screen, so reuse that pose and just reveal the notable overlay; only fall back to a fresh
// detect if arming-time detection failed. The clipboard is no longer read while active, so the
// seed cannot change under us.
function startActiveRecording(): void {
  arming = false;
  if (armTimer) window.clearInterval(armTimer);
  armTimer = undefined;
  clearRedetect();
  // Nothing to do — you've already recorded every notable in this socket for this seed.
  // Flash a brief notice and return to idle instead of locking a screen full of green.
  // (Only when the socket is actually identified, so we never falsely dismiss an unsure guess.)
  if (socketChosen && allRecordedByYouHere()) {
    const at = lockedPose ? underJewelPoint(lockedPose) : undefined;
    lockedPose = null;
    clearLayer();
    updateModeLabel();
    setText(detectEl, IDLE_PROMPT, 'muted');
    setText(statusEl, '', 'muted');
    showToast('Already captured by you.', at);
    return;
  }
  active = true;
  hoverSkill = null;
  updateModeLabel();
  if (lockedPose) renderLocked();
  else void calibrate(); // detection failed while arming — retry now
  void hoverTick();
}

function stopRecording(message: string, kind: 'ok' | 'muted' = 'muted'): void {
  active = false;
  if (hoverTimer) window.clearTimeout(hoverTimer);
  if (cycleTimer) window.clearTimeout(cycleTimer);
  lockedPose = null;
  clearLayer();
  updateModeLabel();
  setText(detectEl, IDLE_PROMPT, 'muted');
  setText(statusEl, message, kind);
  updateProgress();
}

// --- hotkeys (global, from Rust) ---
listen('toggle-run', () => {
  if (active) stopRecording('Recording stopped.');
  else if (arming) cancelArming('Cancelled.');
  else void beginArming();
});
listen('recalibrate', () => {
  if (active || arming) void calibrate();
});
listen<number>('socket-cycle', (e) => {
  if (!active) return;
  manualOverride = true;
  socketChosen = true; // lock to the user's pick
  selectSocket(socketIdx + (e.payload < 0 ? -1 : 1));
  renderLocked();
  // Snap the pose to the socket you land on, debounced so rapid cycling only captures once.
  if (cycleTimer) window.clearTimeout(cycleTimer);
  cycleTimer = window.setTimeout(() => void calibrate(), 350);
});

// OCR the tooltip near the cursor and record what the hovered node became. Auto path only:
// quiet on failure, and reschedules a dwell retry so a slightly-late tooltip still lands.
async function recordNode(p: ProjectedNode): Promise<void> {
  if (!active || !lockedPose || !jewelInfo || ocrBusy) return;
  const node = p.notable;
  if (!reachable(node) || isCovered(node)) return;
  ocrBusy = true;
  try {
    const dpr = window.devicePixelRatio || 1;
    const targetPhysical = { x: p.sx * dpr, y: p.sy * dpr };
    const cur = (await invoke('get_cursor')) as { x: number; y: number };
    const lines = (await invoke('ocr_region', {
      cx: cur.x,
      cy: cur.y,
      w: OCR_BOX_W,
      h: OCR_BOX_H
    })) as OcrLine[];
    // Drop any line over our own status panel: when a tooltip clamps to the top-left it lands
    // beside the panel, which is inside the cursor box, and the panel's stale "Recorded: … →
    // <notable>" text would otherwise match the vocabulary. Line centres are physical px; the
    // panel rect is CSS px, so scale by dpr.
    const m = matchNotable(linesOutsidePanel(lines, dpr), jewelVocab(), targetPhysical);
    if (m && m.confidence >= ACCEPT) {
      commitRecord(node, m);
    } else if (autoTries < AUTO_MAX_TRIES) {
      // Tooltip probably wasn't up yet — let the dwell retry this node shortly.
      autoTriedSkill = null;
      hoverStart = Date.now();
    }
  } catch {
    /* OCR failed this tick — ignore (the dwell may retry) */
  } finally {
    ocrBusy = false;
  }
}

function commitRecord(target: Notable, m: Match): void {
  if (!jewelInfo) return;
  const s = socket();
  recorded.set(recordKey(jewelInfo.seed, target.skill), {
    jewel: jewelInfo.jewel,
    conqueror: jewelInfo.conqueror,
    seed: jewelInfo.seed,
    socketId: s.socketId,
    baseSkill: target.skill,
    nodeId: target.id,
    baseName: target.name,
    resultId: m.id,
    resultName: m.name,
    confidence: m.confidence,
    synced: false
  });
  saveRecords();
  setText(statusEl, `Recorded: ${target.name} → ${m.name} (${Math.round(m.confidence * 100)}%)`, 'ok');
  // Advance to the next notable that still needs capturing (skip covered AND unreachable).
  let next = targetIdx + 1;
  while (next < s.notables.length && !needsCapture(s.notables[next])) next++;
  targetIdx = next;
  void flushSync();
  if (coveredHere() >= reachableNotables().length) {
    void completeSocket();
  } else {
    renderLocked();
  }
}

// Every notable in this socket is captured: flush the last records to the DB, then finish —
// stop recording and return to idle so you can move the jewel and start the next socket.
async function completeSocket(): Promise<void> {
  await flushSync();
  stopRecording(
    'Jewel successfully recorded ✓ — move the jewel to the next socket and press Ctrl+Shift+X.',
    'ok'
  );
}

// Lock a freshly-copied jewel as the active seed for the recording session. Called only from
// the arming handshake after a deliberate Ctrl+C — never from a background poll — so the seed
// is always one the user just picked. The seed is required because the same node transforms
// differently per seed; records are keyed by seed (recordKey).
function bindJewel(info: JewelInfo): void {
  jewelInfo = info;
  const conq = info.conqueror ? ` · ${info.conqueror}` : '';
  setText(jewelEl, `Jewel: ${info.jewel} · seed ${info.seed}${conq}`, 'ok');
  resetTargetToFirstUnrecorded();
  updateProgress();
  // Pull what the community already has for this seed (verified nodes get skipped).
  void loadConsensus(info.jewel, info.seed);
}

// Debug: Ctrl+Shift+S dumps a raw screen capture for mask tuning.
listen<string>('debug-capture', (e) => {
  setText(statusEl, `Saved: ${e.payload}`, e.payload.startsWith('ERROR') ? 'warn' : 'ok');
});

// --- Druid Oracle toggle (panel checkbox) ---
// The panel becomes interactive when the cursor is over it (clickThroughTick flips click-through
// off), so a checkbox is clickable here. stopPropagation on the row keeps the click from also
// starting a panel drag. Ticking it makes the Oracle-only nodes capturable; unticking skips them.
const oracleChk = document.getElementById('oracleChk') as HTMLInputElement;
const oracleRow = document.getElementById('oracleRow')!;
oracleChk.checked = isOraclePlayer;
oracleRow.addEventListener('mousedown', (e) => e.stopPropagation());
oracleChk.addEventListener('change', () => {
  isOraclePlayer = oracleChk.checked;
  localStorage.setItem(ORACLE_KEY, isOraclePlayer ? '1' : '0');
  // Re-point the target at the first node that still needs capture and redraw — Oracle-only
  // nodes appear or disappear as targets with the new reachable set.
  resetTargetToFirstUnrecorded();
  if (active && lockedPose) renderLocked();
  else updateProgress();
});

setText(detectEl, IDLE_PROMPT, 'muted');

// Restore any records from a previous run and start the background sync: retry pending
// observations every few seconds (idempotent upserts), so a flaky network self-heals.
loadRecords();
updateSyncStatus();
setInterval(() => void flushSync(), 5000);
