name: push

permissions: read-all

on: [push, pull_request]

jobs:
  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: 'frontend/.nvmrc'

      - name: Enable corepack
        run: corepack enable

      - name: Install
        working-directory: ./frontend
        run: pnpm install

      - name: Lint
        working-directory: ./frontend
        run: pnpm run lint

      - name: Type check
        working-directory: ./frontend
        run: pnpm run check

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs:
      - lint-frontend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: 'frontend/.nvmrc'

      - name: Enable corepack
        run: corepack enable

      - name: Build frontend
        working-directory: frontend
        run: |
          pnpm install
          pnpm run build
